### ISSUE TITLE
Estudar Open Source

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#1]
ESTUDO/RESUMO

- [x]  Estudar a metodologia Open Source através do link da professora 

- [x] Documentar e resumir a ferramenta para os outros colegas.

**Comment by fernandes-natanael** [comment]
teste🤡

**Comment by DaviMatheus** [comment]
### OPEN SOURCE

1. **O que é ?**
    




2.

**Comment by DaviMatheus** [comment]
### OPEN SOURCE

### 1- **O que é ?**

   Open source , é um projeto que qualquer um pode ver, usar, modificar e distribuir por qualquer motivo. A palavra chave que resumo um projeto Open source é  **colaboração,** pelo fato de que o projetista pode aceitar mudanças de qualquer pessoa no mundo, e também pela Transparência  em que contribuidores podem inspecionar um projeto open source por erros ou inconsistências,  pode-se ver, por exemplo, a  plataforma de exercício de colaboração Exercism, com mais de 350 contribuidores . Muitas pessoas se confundem com isso , mas Open Source **não é só sobre software. Você pode tornar qualquer coisa open source, de conjuntos de dados a livros**.
 
 ### 2.  **Contribuir para um projeto Open Source**

> Contribuir para o open source pode ser uma maneira gratificante de aprender, ensinar e construir experiência em praticamente qualquer habilidade que você possa imaginar.  [Guia de código aberto](https://opensource.guide/pt/how-to-contribute/#melhorar-as-habilidades-existentes)

- Melhorar as habilidades existentes.
-   Encontrar e formar amizades duradouras que possuem o mesmos interesses.
-  Ensinar e ser ensinado por outros mentores.

 ### 3.  **Criando o seu própio projeto Open Source**

> Não há um momento perfeito para tornar o seu trabalho open source. Você pode tornar uma ideia open source, um trabalho em andamento ou mesmo um trabalho que passou anos como código fechado.  [Guia de código aberto](https://opensource.guide/pt/starting-a-project/)


Todo projeto deve incluir as seguintes documentações:

**1.Open source license**
**2. README**
**3. Contributing guidelines**
**4. Code of conduct**


 ### 3.1 **Escolhendo uma licença**

Uma licença open source garante que outros possam utilizar, copiar, modificar e contribuir com o seu projeto sem repercussões. Ela também lhe protege de situações legais problemáticas. **Você deve incluir uma licença sempre que lançar um projeto open source.** Nosso grupo vai trabalhar com a licença [GPLv3 ](https://choosealicense.com/licenses/gpl-3.0/)

 ### 3.2 **Escrevendo um README**
README é  como  uma capa para seu projeto, indo além  de explicar como usar o seu projeto. Eles também explicam porque o seu projeto importa, e o que os seus usuários podem fazer com ele, sendo muitos importantes para despertar interesse no seu projeto para as outras empresas e contribuidores. 

No README é importante tentar responder as possíveis questões que uma empresa esteja tendo em relação ao seu projeto como:

- O que esse projeto faz?

- Por que esse projeto é útil?

**Quando você inclui um arquivo de README no seu diretório raiz, o GitHub irá automaticamente renderizá-lo na página inicial do projeto.** 

 ### 3.3 **Escrevendo suas diretrizes de contribuição**

Um arquivo CONTRIBUTING diz a sua audiência como participar no seu projeto. Por exemplo, você pode incluir informações sobre:

- O que fazer antes de Contribuir?
- Como Contribuir?
- Como criar um relatório de bug
- Adicionando e/ou alterando alguma Funcionalidade
- Como contribuidores devem (ou não devem) entrar em contato com você

 Entre outras informações.

**Usar um tom acolhedor, amigável e oferecer sugestões específicas para contribuições, pode fazer uma grande diferença em fazer com que novos contribuidores se sintam bem vindos e felizes em participar.** 

[Exemplo da diretriz de contribuição do monitor](https://github.com/fga-eps-mds/2020.1-VC_Usuario/blob/master/CONTRIBUTING.md)

 ### 3.4 **Estabelecendo um código de conduta**

Um código de conduta é responsável por criar regras básicas de comportamento para os participantes do seu projeto. Sendo de **extrema importância** no nosso projeto Opens Source , já que esse projeto está sendo lançado para  ser visto por uma comunidade ou alguma empresa. 

> Um código de conduta te dá o poder de facilitar um comportamento saudável e construtivo da comunidade, o que irá reduzir seu estresse como mantenedor. [guia do Código de Conduta](https://opensource.guide/pt/code-of-conduct/)

Assim, no código de conduta tem que ser **claramente exemplificada a promessa de cada participante e os padrões e as responsabilidades que esse grupo possui** 

[Exemplo do Código de Conduta do Monitor ](https://github.com/fga-eps-mds/2020.1-VC_Usuario/blob/master/CODE_OF_CONDUCT.md)

### CONSIDERAÇÕES FINAIS
 Espero ter consigo resumir pelo menos uma parte dessa metodologia tão extensa para os meus colegas de grupo e caso tenha alguma duvida escrevam um comentário nessa issue.

**Links utilizados:**  
 [Guia para começar um projeto](https://opensource.guide/pt/starting-a-project/)
 [Guia de como contribuir](https://opensource.guide/how-to-contribute/)
[Guia de conduta](https://opensource.guide/pt/code-of-conduct/)
