### ISSUE TITLE
Estudar pipeline, CI e CD

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2020.2-CheeryUP#100]
### Descrição:
Estudar CI, CD e o pipeline feita até agora do projeto, além de atualizar o pipeline do projeto.
### Tarefas:

- [x] Estudar sobre os tópicos.
- [x] Atualizar o pipeline.

### Critério de aceitação:
A Issue somente será aceito após verificação de dois outros integrantes e deverá estar coerente com o projeto.

**Comment by mibasFerraz** [comment]
## Geral
Pipeline CD/CI é basicamente uma maneira de automatizar  as entregas dos softwares ao cliente de maneira rápida, eficiente e contínua. Fazer um downgrade fica mais tranquilo caso algo dê errado e o próprio github possibilida o pipeline.
Visualização geral:
![2021-04-12](https://user-images.githubusercontent.com/50213258/114481416-df82d000-9bda-11eb-946b-7755b74e9f0a.png)

### CI 
“CI” sempre se refere à integração contínua, que é um processo de automação para desenvolvedores. Uma CI bem-sucedida é quando novas mudanças no código de uma aplicação são desenvolvidas, testadas e consolidadas regularmente em um repositório compartilhado.
### CD
CD se refere à entrega contínua e/ou à implantação contínua, conceitos relacionados e usados alternadamente às vezes. A implantação contínua, outro significado para “CD”, se refere ao lançamento automático das mudanças feitas por um desenvolvedor do repositório à produção, onde podem ser usadas pelos clientes.
### Fontes
Um vídeo rápido e explicativo pode ser encontrado no [código fonte tv](https://www.youtube.com/watch?v=AZtTd3pFVTY)
Uma explicação escrita pode ser vista no [redHat](https://www.redhat.com/pt-br/topics/devops/what-is-ci-cd)

**Comment by DaviMatheus** [comment]
Muito bom esses videos, agr so falta geral estudar isso para podermos implementar no nosso projeto

**Comment by art1505** [comment]
Muito interessantes os conceitos e vídeos apresentados. Certamente serão fundamentais ao longo de nossa jornada! 🥇 🙏🏽
