### ISSUE TITLE
Estudo de ferramentas para a implementação de gráficos 

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#102]
### Descrição:
Estudo de ferramentas para a elaboração de graficos que serão ultilizados no projeto. 
### Task do que será feito no documento:

- [x] Estudo de linguagem e bibliotecas a serem utilizadas.
- [x] Elaborar um pequeno exemplo de como os gráficos serão implementados no projeto.

### Critérios de aceitação
* implementação correto do que foi feito
* os gráficos tem que ser de fácil interpretação aos psicólogos.

**Comment by Abraao1231** [comment]
# Estudo e prototipo com Chart.js 

Quando o assunto é trabalhar com graficos aparecem varias bibliotecas de javascript para ser realizada essa função em nosso projeto. NO entanto iremos ultilizar a `Chart.js` ela foi escolhida por ser extremante simples de ser usada dependendo da tag canvas do HTML, podendo gerar graficos de linha, pizza barra etc.

![](https://miro.medium.com/max/700/1*HlEcae5mekTKAtb_nRImMQ.png)


Fizemos um pequeno protótipo com django e a biblioteca chart.js para mostrar as possíveis  formas de representação de dados adquiridos pela plataforma através de gráficos.  O prototipo a seguir tem como exemplo mostrar o grau de ansiedade de clientes.

## 1. Primeiro criamos a parte do back end. 

![image](https://user-images.githubusercontent.com/56660914/114332608-ec40ee80-9b1c-11eb-8a0b-2894f45d7715.png)

![image](https://user-images.githubusercontent.com/56660914/114332652-ffec5500-9b1c-11eb-8d8e-224062e0ecc5.png)

## 2. Em seguida a parte onde acontece a magia no front end com dois arquivos.

![image](https://user-images.githubusercontent.com/56660914/114332849-61142880-9b1d-11eb-8767-765282e660c1.png)
Esse template servirá como base para os templates do nosso gráfico. Note que adicionamos nele o CDN do Chart.js.Em seguida o arquivo responsavel pela Tag Canvas e configuração do grafico que no caso será reproduzido um gráfico de barra.
![image](https://user-images.githubusercontent.com/56660914/114333026-c36d2900-9b1d-11eb-92fd-82f0361ddbdb.png)

Note que a variavel ProductsChart é reponsavel pela criação e configurações do grafico como cores valores que  serão ultilizados no grafico e estilo e tipo de grafico. Para alterarmos o tipo de grafico basta alterarmos o valor que o `Type` recebe que nesse caso recebe `bar`.

Em seguida o funcionamento do grafico, mostrando a criação das pessoas com um nivel de ansiedade em seguida o grafico gerado.

1. Criação de dados

![image](https://user-images.githubusercontent.com/56660914/114333369-86556680-9b1e-11eb-80d1-7d77568dfd6a.png)
![image](https://user-images.githubusercontent.com/56660914/114333470-bdc41300-9b1e-11eb-9a50-84a2be936250.png)


![image](https://user-images.githubusercontent.com/56660914/114333496-cc122f00-9b1e-11eb-9f56-a1cef1257a20.png)

**Comment by DaviMatheus** [comment]
Ficou  muito bem explicado, parece mesmo muito simples mesmo , belo trabalho como batedor @Abraao1231 👍
