### ISSUE TITLE
GitHub pages

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#11]
#### Descrição: 
Elaboração da estrutura de documentos do projeto a partir do GitHubPages.

### Tarefas:

- [x] Estudo do funcionamento da ferramenta / aulas com os monitores sobre o assunto.

- [ ] Criação do GitHubPages para o projeto.

### Critério de aceitação:

- Manual para todos integrantes conseguirem informação de fácil acesso.
- O link tem que ser acessível através do github io.

**Comment by DaviMatheus** [comment]
Criamos a Pagina GitHub porém atualizaremos ela  e utilizaremos o mkdocs
