### ISSUE TITLE
Elaborar Documento de Visão

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#12]
### Descrição: 
Criação do documento de visão do projeto, para definir escopo e finalidade do projeto.

### Tarefas:

- [x] Estudar sobre o assunto e escolher uma estrutura (template) a ser seguida.

- [x] Preencher o documento.

### Critério de aceitação:

- Professora deve estar de acordo com o escopo proposto, definindo se é algo tangível em 15 sprint's.

- Todos os integrantes devem ser responsáveis por ao menos um tópico do documento.

- Deve ser submetida a uma revisão de ortografia.
- Deve estar no github pages.

**Comment by NilvanPeres** [comment]
O link para editar o documento simultanemante está [aqui](https://docs.google.com/document/d/1OG6fJW5uNB4VMCqO_HSyR9EAsy1USndfQHYKS4dOTBo/edit). O modelo a ser seguido já foi definido.

**Comment by fernandes-natanael** [comment]
Posicionamento do documento de visão preenchido
