### ISSUE TITLE
Implementação Codecov

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#123]
### Descrição:
Adicionar Codecov a pipeline CI do back e do front.
### Tarefas:

- [x] Implementar Codecov no back-end.
- [x] Implementar Codecov no front-end.
- [x] Adicionar badges no Read.me

### Critério de aceitação:
A Issue somente será aceita se o critério de aceitação for válido.

**Comment by DaviMatheus** [comment]
Coloquei o nosso repositorio no codecov nesse [link](https://app.codecov.io/gh/fga-eps-mds/2020.2-CheeryUP/) acessem la depois ,quando tiverem tempo tentem colocar um teste que ainda n foi testado, estamos atualmente nos 94%, estamos em busca dos 100% 🤓 ☝️
