### ISSUE TITLE
Criação das paginas restantes do front.

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#128]
### Descrição:
Criação das paginas no frontend seguindo o protótipo de alta fidelidade, criando todas as paginas, menos as referentes aos graficos.

### Tarefas:

- [x] Refatorar paginas de Login.
- [x] Pagina do Registro da Consulta.
- [x] Pagina de Atualizar dados do psicólogo.
- [x] Pagina de Atualizar dados do paciente.
- [x] Pagina de Atualizar senha.
- [x] Outras. 
- [x]  Adicionar responsividade para todas as páginas.

### Critério de aceitação:
Deverá apresentar padronizações das telas e ter como base o protótipo de alta fidelidade, onde todas as paginas deverão ter responsividade.

**Comment by antoniotoineto** [comment]
Páginas de Cadastro de Paciente e Atualização de Dados de Paciente adicionadas.
