### ISSUE TITLE
Criação documento de Arquitetura

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#13]
### Descrição:
Elaboração do documento de arquitetura do projeto, para definir quais softwares serão utilizados no desenvolvimento do projeto,

### Tarefas:

- [x] Estudar sobre o assunto e escolher uma estrutura (template) a ser seguida.

- [x] Preencher o documento.

### Critério de aceitação:

- Pareamento dos integrantes para o desenvolvimento do documento.

- Deve ser submetida a uma revisão de ortografia.
- Deve estar no github pages.

**Comment by NilvanPeres** [comment]
O link para os integrantes modificarem simultaneamente está [aqui](https://docs.google.com/document/d/1cfI5MBjWi99CLA7mJtjtJ3sZp1-Umyiy04fpQLYIhTw/edit?usp=sharing). A estrutura a ser seguida já foi decidada.

**Comment by DaviMatheus** [comment]
Adicionei o templete de documento de arquitetura no docs

**Comment by NilvanPeres** [comment]
Adicionado a estrutura do documento de arquitetura em nosso repositório.
