### ISSUE TITLE
Reunião com psicóloga

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/2020.2-CheeryUP#132]
### Descrição:
Coletar dados de psicometria com a psicóloga indicada pela professora Carla.
### Tarefas:

- [x] Coleta dos dados.

### Critério de aceitação:
Obter resultados satisfatórios com a reunião.

**Comment by DaviMatheus** [comment]
O @NilvanPeres entrou em contato com o novo email que professora mandou(agr com o contato certin), e conseguimos essas metricas: e conseguimos esses texto 
![image](https://user-images.githubusercontent.com/54643148/116765402-3d951d00-a9fb-11eb-84af-430ee0f98cc9.png)

todos deram uma lida, mas por consenso mutuo, decidimos continuar com as psicologos que ja tinhamos entrado em contato [antes ](#91).

**Comment by DaviMatheus** [comment]
com isso dito, eu e o @Abraao1231  conseguimos marcar uma reunião com a psicóloga do grupo e com uma amiga dela.

**Comment by DaviMatheus** [comment]
## ALGUNS PONTOS PENSADOS
atualização atual:
- indice dobrou
- pacientes em riscos
- segunda onda
- não estam conseguindo fazer um atendimento de uma hora 
- atenter 8 pacientes por dia 
- algo rapido

**Comment by Abraao1231** [comment]
Eu e o @DaviMatheus entramos em contato com a psicologa Vanda e obtivemos muito sucesso em relação a implementação da consulta e também em relação ao gráficos da plataforma e também alguns alertas ao psicologo sobre determinados riscos que um paciente pode estar passando. Entre os gráficos mencionados pela psicologa os principais sao:
- evolução do cliente
- estabilidade emocional do cliente
- qualidade de vida do cliente
