### ISSUE TITLE
US08 - Atualizar Conta

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#135]
### Descrição
Eu, como ***psicólogo***, gostaria de ***atualizar minha conta***  para ***gerenciar melhor minhas informações**.

### Critérios de Aceitação
- Atualizar meus dados de forma segura e simples.
- Estiver rodando e funcionando corretamente.
- Alterar a minha senha. 

***Estrutura dos campos de alterar conta levada em consideração foi essa***:
![image](https://user-images.githubusercontent.com/54643148/116797021-8f02e200-aab7-11eb-9d6d-8c14a494521f.png)

***Estrutura dos campos de alterar senha em consideração foi essa***:
![image](https://user-images.githubusercontent.com/54643148/116797035-aa6ded00-aab7-11eb-98a3-b4cf8b42870d.png)

### Comportamento esperado  

- [x]  Capacitar a API para atualizar a conta.

- [x] Criação do endpoint para alterar a conta.(put)

- [x] Capacitar a  API para alterar a senha.

- [x] Criação da tela de front-end.

- [x] Criação da tela de alterar senha no front-end.

- [x] Capacitação do frontend para requisições

- [x] Envio do formulário do front para o back.

- [x] Comunicação responsiva front-end, back-end e do usuário psicologo.

**Comment by NilvanPeres** [comment]
https://user-images.githubusercontent.com/54211866/118695393-86aee480-b7e3-11eb-950a-e42ccf560914.mp4

**Comment by NilvanPeres** [comment]
A funcionalidade está implementada, o usuário consegue atualizar os dados que foram fornecidos no cadastro. Graças as mudanças no back, usaremos o patch para a atualização. O CSS da página tá horrível, a issue será finaliza após algum dos integrantes consertarem @art1505 @fernandes-natanael
