### ISSUE TITLE
Analisar possiveis estruturas de RoadMaps

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#14]
### Descrição:
Elaboração do RoadMap do Projeto, Product Owner, Scrum Master, DevOps, Arquiteto.

### Tarefas:

- [x] Estudar sobre o assunto e escolher uma estrutura (template) a ser seguida.

### Critérios de aceitação:

- Cada integrante montar a estrutura do documento de acordo com sua escolha/função no projeto. (Adiante, a função dos membros será flexível, existindo a possibilidade de trocas).

**Comment by DaviMatheus** [comment]
#### ROADMAP 

- eu achei alguns vídeos que explicam bem como que funcionam e o que é o [Roadmap](https://www.youtube.com/watch?v=cZEV9CLUd2Q&ab_channel=Roadmunk)  e um [blog](https://gobacklog.com/blog/roadmap/)  

-  no video ele usa a plataforma [roadmunk](https://roadmunk.com/)

<p align = "center"> &emsp;&emsp; <img src="https://images.squarespace-cdn.com/content/v1/5c38e43c1137a62fe35583ff/1585730217626-9K9PSC8W4G2RCSS5YLK2/ke17ZwdGBToddI8pDm48kLxnK526YWAH1qleWz-y7AFZw-zPPgdn4jUwVcJE1ZvWEtT5uBSRWt4vQZAgTJucoTqqXjS3CfNDSuuf31e0tVFUQAah1E2d0qOFNma4CJuw0VgyloEfPuSsyFRoaaKT76QvevUbj177dmcMs1F0H-0/roadmunk-logo.png" width="150" height="150"/> </p>

-no blog ela fala da plataforma [aha!](https://www.aha.io/)

<p align = "center"> &emsp;&emsp; <img src="https://res.cloudinary.com/modus-create-inc/images/f_auto,q_auto/w_2000,h_1000/v1610397521/Aha_Blue_TransparentBG/Aha_Blue_TransparentBG.png" width="150" height="150"/> </p>

- tambem achei um video bem interessante falando sobre o Jira ([video curto](https://www.youtube.com/watch?v=gIxP_0QZuBQ&ab_channel=ETAWarden)) ([video longo](https://www.youtube.com/watch?v=HJdfiy2UoCE&ab_channel=Atlassian) pra quem quiser ser aprofundar).


<p align = "center"> &emsp;&emsp; <img src="https://www.atlassian.com/br/dam/jcr:e33efd9e-e0b8-4d61-a24d-68a48ef99ed5/Jira%20Software@2x-blue.png" width="400" height="100"/> </p>

Os projetos que podem nos nortear são: 
- [Gerenicia_Mais](https://github.com/fga-eps-mds/2018.1_Gerencia_mais/tree/master/docs/documentos/RoadMaps) Não gostei tanto assim do layout, mas podemos ver como que vamos ter que separar e determinar o roadmap.
- [ArBC](https://jlucassr.github.io/ArBC-Pages/eps/roadmap/) Um projeto muito bem feito.
- [Ziguen](https://github.com/fga-eps-mds/2020.1-Ziguen/blob/master/docs/wiki/Roadmap.md) um mais simples mais tambem muito bom

**Comment by DaviMatheus** [comment]
@juninhigh @antoniotoineto @fernandes-natanael @Abraao1231 @art1505 depois devemos por favor vejam esses videos para que na proxima sprint realizarmos o nosso RoadMap
