### ISSUE TITLE
E3 - Implementação dos gráficos

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#140]
Épico relacionado a implementação dos gráficos de  acordo com as informações do paciente e de suas consultas.

**Comment by Abraao1231** [comment]
Os gráficos foram implementados de acordo com os dados que são retirados das consultas, que foram feitos e avaliados pelas psicologas que nos orientaram no projeto. Os gráficos criados foram: Qualidade de vida, evolução do paciente, desempenho do psicologo com determinado paciente, gráfico de regiões entre outros .
