### ISSUE TITLE
US13 - Implementação dos gráficos em relação ao paciente

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#141]
### Descrição
Eu, como ***desenvolvedor***, gostaria de ***implementar gráficos em relação ao paciente*** para ***os usuários da plataforma***.

### Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)
- Os gráficos devem estar calculados com os parâmetros que a psicóloga definiu 
- Deveram ser de fácil compreensão e práticos.
- Serem implementados corretamente

***Estrutura de métricas utilizadas foram esses***:

            PESO:   3
            - evolução do cliente = ”linha” : (peso maior para: qualidade de vida, humor e estabilidade emocional)
            - estabilidade emocional = ”linha” (convivi-o familiar e amigos, capacidade de lidar com situações difíceis )
            - qualidade de vida = ”linha” (interesse pela vida, exposição de risco, qualidade nutritiva)
            - média de sintomas do paciente “Pizza”
            produtividade do psicólogo “dognut”
            

### Comportamento esperado  

- [x] Gráfico de Pizza aumentar e diminuir de acordo com o numero de regiões, de consultas e de pacientes

- [x] Gráficos de linha, diminuindo e aumentado de acordo com os dados da consultas.

**Comment by Abraao1231** [comment]
Foram implementados diversos gráficos para o psicologo ter uma melhor gestão de consultas de seus pacientes segue as imagens abaixo:

Gráfico de avaliação de consulta:
![image](https://user-images.githubusercontent.com/56660914/117355999-a52eea80-ae89-11eb-9448-b68117a1fce2.png)

Gráfico de avaliação média do paciente:
![image](https://user-images.githubusercontent.com/56660914/117356098-c1328c00-ae89-11eb-8f59-91726d4b11e5.png)

Gráfico de estabilidade emocional do cliente:
![image](https://user-images.githubusercontent.com/56660914/117356174-d7404c80-ae89-11eb-8dea-cfec63e801db.png)

Gráfico de evolução do cliente:
![image](https://user-images.githubusercontent.com/56660914/117356255-e7582c00-ae89-11eb-89d4-b19761ad6bd8.png)

Grafico de Produtividade do psicologo:
![image](https://user-images.githubusercontent.com/56660914/117356323-f808a200-ae89-11eb-95d0-4806aac40b4f.png)

Grafico de Qualidade de vida do cliente:
![image](https://user-images.githubusercontent.com/56660914/117356411-11a9e980-ae8a-11eb-8b5a-882e67ec43b5.png)
Gráfico de pacientes em cada região:
![image](https://user-images.githubusercontent.com/56660914/117356467-24242300-ae8a-11eb-891d-2e76ba316b7d.png)
