### ISSUE TITLE
US14 - Visualização dos gráficos 

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#142]
### Descrição
Eu, como ***psicólogo***, gostaria de ***ver o gráficos da evolução do paciente*** para um ***melhor entendimento sobre o paciente e sobre as consultas***.

### Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)
- Deverá ter o campo ...;
- Deverá calcular/apresentar ...;
- Funcionalidade testada;

### Comportamento esperado  

Ex :  

- [ ] O usuário deve conseguir recuperar sua senha.  

- [ ] O usuário será redirecionado quando não conseguir lembrar sua senha...

**Observações**

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by NilvanPeres** [comment]
https://user-images.githubusercontent.com/54211866/118706588-ed39ff80-b7ef-11eb-8a5d-b06aa47c2a00.mp4
