### ISSUE TITLE
US16 - Visualização dos dashboards 

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#146]
### Descrição
Eu, como ***psicólogo***, gostaria de ***visualizar os dashboards*** para um ***melhor entendimento sobre o paciente e sobre os pacientes***.

### Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)
- Deverá ter o campo ...;
- Deverá calcular/apresentar ...;
- Funcionalidade testada;

### Comportamento esperado  

Ex :  

- [ ] O usuário deve conseguir recuperar sua senha.  

- [ ] O usuário será redirecionado quando não conseguir lembrar sua senha...

**Observações**

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by NilvanPeres** [comment]
Gráficos linhas para evolução dos pacientes foram implementadas, e grafico pizza para as regiões de cada paciente, e gráfico doughnut para a produtividade das consultas.
