### ISSUE TITLE
Plano de comunicação entre os membros

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#16]
### Descrição:
Determinar quais serão as ferramentas de comunicação utilizadas pelo grupo.

### Tarefas: 

- [x] Criar um documento indicando quais são as ferramentas escolhidas.

### Critério de aceitação:

- Todos membros devem saber utilizar as ferramentas propostas.

**Comment by DaviMatheus** [comment]
@art1505 @Abraao1231 @juninhigh @fernandes-natanael @antoniotoineto Gente, esse é o [documento de comunicação](https://github.com/fga-eps-mds/MDS-2020-2-G7/blob/main/docs/COMUNICATION.md), me certifiquei de que todos soubessem como mexer em cada um, mas caso tenham duvida só mandar um comentário  😄
