### ISSUE TITLE
Definir tecnologias e funções dos integrantes

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#17]
### Descrição:
Delegar aos membros as funções que cada um vai desenvolver, e escolher as tecnologias para elaborar o projeto.

### Tarefas:

- [x] Definir tecnlogoias do back/front.

- [x] Divisão das funções do projeto: ProductOwner/ScrumMaster/DevOps/Front/Back.

### Critérios de aceitação:

- Afinidade ou vontade de aprender a tecnologia/função proposta.

**Comment by DaviMatheus** [comment]
## [Tecnology](https://github.com/fga-eps-mds/MDS-2020-2-G7/blob/main/docs/info/Tecnology.md)

-  Em nossos Dailys decidimos optar para o front JavaScript React e no back Python Django.
- Banco de Dados SQL MySQL

## Conhecimentos 
**Fizemos um [quadro](https://user-images.githubusercontent.com/54555684/107799437-2b7cda00-6d3c-11eb-90a6-47abd2ae5fc1.PNG) para definirmos o nível de conhecimento que cada um dos membros possuía.**

-  75%  possuem afinidade com Python , mas falta estudar Django.
- 66,66% possuem afinidade  com JavaScript, porém falta estudar React
- Agora SQL precisaremos de um estudo mais aprofundado para realizar o Banco de Dados
