### ISSUE TITLE
Termino do Postmortem

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#175]
### Descrição:
Termino da issue #161, adicionando sentimentos da equipe e documentação da Release 2
### Tarefas:

- [x] Entrega Release 2
- [x] Sentimentos da Equipe
- [x] Revisão e Correção de erros

### Critério de aceitação:
Deverá apresentar a estrutura completa do documento.

**Comment by antoniotoineto** [comment]
## Referente ao sentimento da equipe:
Eu diria que MDS foi a matéria que me introduziu de vez no mundo da Engenharia de Software. Desde do começo do curso eu me deparava com diversas matérias que impulsionam o desenvolvimento de habilidades que um engenheiro de Software deve dominar, uma matéria nos ensinava a lógica de programação, a outra matéria era responsável pela lógica matemática por trás disso, e assim vai... mas eu sempre treinava habilidades distintas, que um dia se combinariam. Foi aí que me deparei com MDS, a matéria que juntou tudo isso e muito mais.

MDS me ensinou desde uma boa comunicação em equipe até boas horas na frente do computador pesquisando sobre uma ferramenta ou alguma tecnologia específica. MDS contempla tudo de uma vez, desenvolvendo de forma ampla do estilo de trabalho que vamos encontrar no mercado de trabalho. MDS é uma matéria bastante trabalhosa, mas que todo os conhecimentos e habilidades adquiridas compensam o trabalho duro. Essa matéria foi responsável por uma mudança, tanto na minha visão como na minha postura como Engenheiro de Software.

Como integrante da equipe, me sinto grato pela oportunidade do trabalho em equipe, e o desenvolvimento nessa habilidade. Tudo isso me mostrou que o trabalho em equipe é uma forma tremendamente magnífica para o aprendizado. No mais, me considero um integrante proativo no projeto, mas confesso que tive alguns momentos de distração, que custaram mais trabalho depois.

Portanto, a matéria têm sido muito gratificante, pois é nítido que todo o trabalho duro realizado no semestre foi sendo projetado em novas e essenciais habilidades, pensamentos e conhecimentos como um aluno de Engenharia de Sofware

**Comment by Abraao1231** [comment]
## Sentimentos em relação a equipe
No inicio da disciplina eu e o grupo estávamos meio perdidos em relação ao que tinha que ser feito,já que nenhum de nós não tínhamos experiencia em projetos mais profissionais e muito menos sobre as tecnologias que iriamos ultilizar em nosso projeto , porém, apesar de tudo isso
na release 1 tivemos um excelente trabalho em equipe o que nos ajudou muito na organização do projeto e também a entender melhor as metodologias de desenvolvimento de software mais adequadas para o nosso projeto. 


Mas a partir da release 2 tanto eu como o Davi perdemos muito contato com a galera do frontend
que acabou deixando agente bastante preocupado em relação a conclusão do projeto. Acho que uma questão muito interessante do projeto foi manter um contato constante com o nosso cliente para saber o que deveria ser  feito e realizar essa comunicação foi um tanto confusa já que não sabemos nada sobre psicologia e os psicólogos que tivemos contato não sabiam muito sobre como falar no que eles estavam pensando tanto que uma delas disse que agente tava lá tentando fazer mais com que agente entendesse o que o outro dizia do que realmente fazer e implementar o projeto. Mas no final das contas agente conseguiu entender o que se passava na mente de cada um.

E apesar de todas essas dificuldade fiquei contente com o resultado na disciplina e hoje com tantas ferramentas e tecnologias estudadas, metodologias usadas, trabalho em grupo e com uma comunicação direta com um possível cliente, entendo sua importância em um curso como esse.

**Comment by mibasFerraz** [comment]
## Sentimentos em relação a equipe e matéria
Antes de conhecer a disciplina, já sabia que não seria fácil. O que eu não sabia era que ia ser tão desgastante assim. 
Comecei no grupo 3 e tivemos um desempenho tão insatisfatório que a melhor opção foi desfazer o grupo e realocar os membros para outros grupos. Nessa jogada eu vim parar no grupo 7. Cheguei aqui completamente perdido com a matéria e com o que o grupo estava desenvolvendo. Tive menos tempo que os demais para poder estudar as tecnologias utilizadas no projeto e isso acabou tornando a matéria mais corrida ainda. Por conhecer um pouco de python, acabei entrando no back-end para aprender Django e ajudar no projeto. Fiz algumas funcionalidades, mas como o Abraão e Davi mandam pra caramba e o front-end tava precisando de ajuda, troquei de time sem saber quase nada sobre javascript, hmtl e css. Aí tive menos tempo ainda pra aprender essas tecnologias e ajudar a galera no front. Como tinham mais coisas pra fazer aqui, acabei sendo mais produtivo no front que no back. <br>
Quanto às equipes, definitivamente não tive uma relação boa com o primeiro grupo. Porém, com o grupo 7 foi totalmente diferente. Entrei sem conhecer ninguém e eles foram muito receptivos e tranquilos comigo. O grupo se comunica muito bem (as vezes bem até demais com reuniões no sábado ou domingo kkkkk), soubemos absorver as ausências no decorrer do semestre e sempre houve o respeito e solidariedade. O sentimento do cansaço agora no fim é grande e já estou sem muita paciência pra terminar as pendências, mas quando eu olho o resultado final e vejo como que ta ficando legal dá um ânimo. Valeu, galera!<br>
Em suma, aprendi <b>muito</b> mais do que eu esperava com essa matéria. Desde a relação com meus colegas de grupo até as diversas linguagens que nunca tinha visto antes. O crescimento foi notório e isso vai dar pra ver naquela pesquisa do que eu sabia e o que sei agora. Em especial gostaria de agradecer o Abraão, Davi, Antônio e Junin por terem me ajudado pelo menos alguma vez no decorrer da matéria de MDS e também para a professora Carla e a monitora Giulia por terem me ajudado no início do semestre.

**Comment by fernandes-natanael** [comment]
## Sentimentos em relação projeto
No começo do projeto nosso grupo estava muito perdido com relação às tecnologias, pois a maior parte apenas tinha conhecimento de tecnologias vistas na faculdade, C e Java, e que no momento em que precisamos utilizar tecnologias mais atuais do mercado de trabalho, acredito que isso assustou a todos do grupo, contudo, acredito que conseguimos um resultado satisfatório para o projeto.

Em relação ao esforço equipe, acredito que todos mostraram um esforço considerável, ressalvas ao Nilvan e ao Davi, e acredito que eu tive um baixo desempenho em alguns momentos do projeto. Sobretudo, por ser o meu primeiro contato com o uso de 'frameworks' e a minha falta de conhecimento sobre python e javascript, além de que inicialmente eu estava na equipe do back-end e tive que migrar para o front-end, gerou um certo desanimo em mim, com isso, a minha comunicação e contribuição com o projeto decaíram bastante. Outro fator, parte da equipe já se conhecia anterior mente o que ajudou na comunicação

Assim sendo, MDS para mim, foi uma visão do mercado de trabalho, e me mostrou que eu estou apenas no início da minha carreira e que ainda tenho muito o que aprender muito sobre a Engenharia de Software para ser um bom profissional. Além disso, identifiquei graves problemas de comunicação que eu tenho e que preciso para o meu desenvolvimento pessoal, não apenas no ambio de trabalho, mas também relações interpessoais.

Definindo os meus sentimentos sobre o trabalho em poucas palavras seria um projeto onde toda a equipe é formada por estagiários, onde todos querem aprender, mas acabam só fazendo bobeira no código.

**Comment by art1505** [comment]
## Sentimentos em relação a equipe e matéria
Antes de iniciar o semestre, já tinha conhecimento do tempo e atenção que seriam grandemente demandados pela disciplina. Contudo, dividi-la com outras 7 foi, sem dúvidas, um desafio à parte.
Apesar da dificuldade de adaptação com toda a metodologia, encarei este desafio com muita satisfação, sabendo da importância de MDS no que diz respeito à uma imersão mais profunda nas demandas a serem correspondidas no mercado de trabalho.

Apesar de já ter conhecimento de algumas linguagens de programação, meu conhecimento parecia muito aquém do esperado para uma boa contribuição e desenvolvimento do projeto. Sabendo disso, não medi esforços para tentar evoluir e cumprir com o que me era designado, ainda que lentamente. Para que isto se efetuasse, a comunicação, compreensão e colaboração dos meus companheiros constituíram fatores determinantes. 

Findo a disciplina com um sentimento de dever cumprido que vai muito além da simples realização do projeto proposto. Na realidade, a importância da comunicação e trabalho em equipe aliadas ao esforço contínuo para nossa evolução como futuros engenheiros de software constituíram os pontos centrais de nossa caminhada até o etágio atual. Apesar de, claramente, nos encontrarmos em níveis de prepraração distintos, temos todos a característica comum de saírmos bem mais capacitados do que entramos.

**Comment by DaviMatheus** [comment]
## Referente ao sentimento da equipe:

Ao contrário de todos, eu não tinha noção nenhuma de como seria essa matéria, cheguei ás cegas, eu só sabia que tinha que fazer um trabalho em grupo, e caso esse grupo seja ruim , era melhor trancar. Eu já tinha péssimas experiências de trabalho em equipe saindo de OO, não  queria ter que fazer tudo de novo sozinho. Com isso em mente, propus para alguns dos meus amigos fazerem um trabalho junto, que pelo menos se precisaríamos trancar, nós trancamos juntos, assim juntei o Antônio, Natael,  o Arthur, e o parceiro que sofreu junto comigo em OO o Nilvan. Conseguimos ótimos parceiros como o Lucas e o Abraao, que me ajudou a fazer o backend.

Conseguimos entregar uma Release 1 muito boa, porém acabamos ficando mais desleixados e a produtividade da equipe diminui-o bastante, principalmente em relação ao frontend, em que o back estava praticamente pronto, o front estava apenas começando.

Com isso, tive algumas dificuldades em reforçar produtividade, ou falar algumas coisas já que a maioria são meus amigos, e eu sabia o quão difícil estava o semestre para todo mundo, porém todo mundo conseguiu dar a volta por cima e realizar um otímo trabalho, em que cada um realizou sua parte.

**Comment by NilvanPeres** [comment]
### Referente ao sentimento da equipe e da matéria:
MDS para mim se resume em um MIX de sentimentos. Ao mesmo que foi a matéria que mais me proporcionou conhecimentos, que mais me desafiou, que me ensinou a ser um pesquisador melhor. Também foi a matéria também me sugou, cheguei a um nível de estresse alto, mas no final das contas saio bastante satisfeito pelos conhecimentos que adquiri nas ferramentas e nas linguagens.

Também fiquei orgulhoso pelo grupo ter conseguido implementar as funcionalidades, pessoalmente achei extremamente desafiador por não conhecer absolutamente nada das ferramentas e linguagens que precisávamos para desenvolver o projeto. Seguimos a máxima de “feito é melhor que perfeito”, mas tenho plena consciência das diversas melhorias que poderíamos implementar, porém que o tempo que obtemos, foi o melhor que conseguimos. 
A matéria é a mais útil que peguei porque me proporcionou um “norte” para ser um bom desenvolver, foram introduzidos todos os termos que eu precisava conhecer para escolher um caminho, e evoluir nele. Identifiquei muitas falhas em relação a como desenvolvo códigos e qualidades, mas vou evoluir nesses quesitos.

Em relação ao grupo também foi um mix de sentimentos, apesar do back-end ter conseguido manter uma fluidez e ritmo de trabalho louvavéis, no front a produtividade não foi nada legal. Me senti extremamente sobrecarregado no final do semestre por ter que realizar papeis de SM, DevOps, e ter que desenvolver a grande maioria das partes de lógica do front-end. Se eu tirasse alguns dias para estudar para maratona de provas de outras matérias, parecia que quase nada acontecia no front.
