### ISSUE TITLE
Termo de Abertura do Projeto

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#18]
### Descrição:
Elaborar o documento de Termo de Abertura do Projeto (TAP).

### Tarefas:

- [x] Estudar e escolher uma estrutura(template) de TAP a ser seguido.

- [x] Preencher o documento.

### Critérios de aceitação:

- Documento deve ser revisado por outra pessoa que não está responsável pelo mesmo.

- Deve estar no github pages.

**Comment by antoniotoineto** [comment]
Finalizado o Termo de Abertura do Projeto.
