### ISSUE TITLE
Docs da sprint 01

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#19]
### Descrição:
Criar o documento da sprint 1.

### Tarefas:

- [x] Criação do planning da sprint 1.
- [x] Criação do review da sprint 1.

### Critérios de aceitação:

- O planning deve ter um quadro com os conhecimentos dos membros e a função que cada um escolheu.

**Comment by antoniotoineto** [comment]
Conclusão da Sprint 1 Planning. Sujeito à mudanças.
