### ISSUE TITLE
Política de issues, commits e pull requests.

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2020.2-CheeryUP#20]
### Descrição:

Política de issues, commits e pull requests.

### Tarefas: 

- [x] Adicionar template de issues, commits e pull requests.

### Critério de aceitação: 
- Todos os membros deverão seguir o formato deste template.
- Criar template de issues, commit e PR, e adicionar no diretório de documentos.

**Comment by fernandes-natanael** [comment]
## Estrutura para Issue

### Descrição:
Uma descrição detalhada sobre o que será feito.
### Tarefas:

- [x] Tarefa 1 ( cumprida ).
- [ ] Tarefa 2 ( não cumprida ).

### Critério de aceitação:
A Issue somente será aceita se o critério de aceitação for válido.

**Comment by fernandes-natanael** [comment]
## Estrutura para Pull Request
### Issues relacionadas:
- #Numero_da_issue
### Alterações Realizadas:
_**`Tipo de alteração`**_
- Atualização da documento do projeto.
- Resolução de bugs.
- Implementação de novas funcionalidades.

### Descrição:
Descrição do que este requeste irá alterar no projeto.

**Comment by NilvanPeres** [comment]
### Estrutura para Commits

- categoria_nome do commit_#issueQueRefereaoCommit.
- Exemplo: bugs_correçõesFront #10

Categorias:

_**del**_: Deletando algum arquivo/pasta e afins.
_**format**_: Formatação no código.
_**docs**_: Adição/atualização de algum documento.
_**bugs**_: Correção de algum bug.
_**feat**_: Adição/atualização de nova funcionalidade.
_**test**_: Adição/modifição de um teste.
_**refact**_: Refatoração do código.

**Comment by NilvanPeres** [comment]
@Abraao1231 @art1505 @DaviMatheus @antoniotoineto. Galera, deêm uma olhada em como vai ser nossos commit's, PR's, e Issues, todas deverão seguir esse padrão.
