### ISSUE TITLE
Feedback 1

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2020.2-CheeryUP#23]
# Feedback Geral
 Olá pessoal, estou aqui para dar uma ajudinha no andamento do projeto de vocês!
De modo geral, quero dar os parabéns a vocês! Estão bem empenhados, presentes em todas as reuniões, se organizando e estudando bastante, isso é ótimo! Continuem nesse bom ritmo que é sucesso.
 Gostei bastante de como fizeram o planning da sprint 1 e que incluíram o quadro de conhecimentos.
 Gostei também dos templates de issues e commits [(outro exemplo de commit se tiverem interesse)](https://github.com/fga-eps-mds/2020.1-Ziguen/blob/master/docs/templates/commit_template/commit_policy.md).
 >>>
# Práticas
 * [x]  Quantidade mínima de issues está de acordo com o esperado (pelo menos 1 issue por membro por sprint)
 * [x]  As issues estão bem escritas (alguém que não faz parte da equipe é capaz de entender e implementar a solução)
 * [x]  Os commits estão atômicos (uma tarefa por commit)
 * [x]  Os commits estão bem comentados
 * [x]  O repositório está organizado
 * [x]  O ritmo do projeto está de acordo com o esperado
 * [ ]  Estão comentando nas issues
 >>>
 # Sugestões de Melhorias
 *  Criem menos issues por sprints (de acordo com o que vocês darão conta)
 *  Não sobrecarreguem apenas um membro (dividam as tarefas igualmente)
 *  Comentem nas issues, abram discussões sobre o assunto e registrem o que está sendo feito (toda a equipe deve comentar, para que a professora veja a atividade de cada aluno)
 *  Coloquem o template de issues e PRs dentro da aba Insights / Community para facilitar e automatizar suas criações

**Comment by NilvanPeres** [comment]
Muito obrigado pelo feedback @gabrielapivetta. Essa sprint realmente colocamos muitos objetivos/issues para serem realizados, estará documentado na review da sprint 1 nossas principais dificuldades. E nos adaptaremos para isso não ocorrer novamente.

**Comment by DaviMatheus** [comment]
Valeu pela ajuda, tentaremos mostrar melhor  a nossa transparência e o nosso processo a partir dos comentários das issues, algo que realmente esta faltando fazer.

**Comment by antoniotoineto** [comment]
Obrigado pelo feedback @gabrielapivetta !! Estaremos sempre tentando melhorar cada vez mais... principalmente nos comentários das issues e da boa comunicação em equipe.
