### ISSUE TITLE
Elaboração da ATA de reuniões

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2020.2-CheeryUP#27]
Descrição:
 Elaborar uma ATA para controlar as reuniões diárias do grupo, inserindo data, horário, participantes e meio de comunicação.

Tarefas:

- [x] Criar uma ATA para as reuniões.

- [x]  Preenchê-la com as informações de cada reunião.

Critérios de aceitação:

- Dados das reuniões devem estar corretos.

**Comment by antoniotoineto** [comment]
ATA criada. Sujeita à atualizações.

**Comment by NilvanPeres** [comment]
Massa o documento, @antoniotoineto. Eu só criei uma pasta para atas para ficar mais tranquilo ir adicionando novos documentos de ata, caso seja necessário...

**Comment by DaviMatheus** [comment]
Ficou bom,  a gente só precisa se lembrar de atualizar  🧑‍⚕️
