### ISSUE TITLE
Estudar backlog de produto

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2020.2-CheeryUP#28]
### Descrição:
Descobrir o que é backlog de produto é qual a sua importância para o desenrolar da equipe.
### Tarefas:

- [x] Aprender sobre como funciona o Backlog de produto.
- [x] Resumir de forma sucinta em comentários.

### Critério de aceitação:
Resumo qualificado para o final da issue.

**Comment by fernandes-natanael** [comment]
## Product Backlog 
A backlog do produto é uma lista gerenciada pelo PO, Product Owner, onde o PO é responsável de catalogar as necessidades do cliente e listar as necessidades por prioridade de implementação para a construção do produto final.

Além disso, a backlog do produto é algo dinâmico, pois ao longo do projeto alguma implementação pode não resolver nada para o cliente ou o pedido do cliente não resolve o problema proposto, logo a backlog tem que evoluir como o produto em si, para que se adeque ao novo formato e tenha a utilidade apropriada.

Portanto, o Product Owner sempre fará uma análise de riscos, com a finalidade de não atrasar ou não sobrecarregar o projeto, por consequência, é notável que o gerenciamento do backlog será crucial para o projeto.

### Gerenciamento de backlog 
Antes de iniciar a implementação é preciso analisar a quantidade de coisas a se fazer e a capacidade de se fazer, logo, para evitar transtornos e entregas impossíveis aqui vai algumas dicas e para organização do PO com o devteam.

1. Dividir as funcionalidades em baixa, média e alta prioridade.
2. Criar critérios objetivos que afetem de modo positivo a classificação e priorização.
3. Priorizar funcionalidades em uma fila.
4. Detalhe apenas o necessário.
5. Use o blacklog como uma agenda para tomada de decisões da equipe.
6. Reorganize semanalmente a prioridade de funcionalidades.

Eu sei que virou um papo de ****coach**** aqui no final, mas sempre é bom manter padrões e tentar controlar o processo de produção.

**Comment by fernandes-natanael** [comment]
***`Vídeos Recomendados`***
- [Vídeo curto](https://www.youtube.com/watch?v=Z667-Y4btsw);
- [Vídeo médio](https://www.youtube.com/watch?v=BLX-wtpQfdw);
- [Vídeo médio-grande](https://www.youtube.com/watch?v=V8Rg8JLyq9s);

**Comment by DaviMatheus** [comment]
Boa pesquisa ❤️
