### ISSUE TITLE
Docs da Sprint 02

### ISSUE THREAD

**Issue by art1505** [fga-eps-mds/2020.2-CheeryUP#29]
### Descrição:
Criar o documento da sprint 2.

### Tarefas:

- [x] Criação do planning da sprint 2.
- [x] Criação do review da sprint 2.

### Critérios de aceitação:

- O planning deve ter boa descrição do que deve ser seguido ao longo da sprint.
- A review deve ser fidedigna ao andamento da sprint, detalhando pontos positivos e negativos encontrados na mesma.

**Comment by NilvanPeres** [comment]
Criação do planning da sprint 2 adicionada no repositório. @art1505 para o review vamos nos reunir no dia 25/fev para adição de novos tópicos, como a gráfico de burndown e review do ScrumMaster.

**Comment by art1505** [comment]
Certo!
