### ISSUE TITLE
Implementar Docsify no GitHub Pages

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#30]
Descrição:  

Estudar Docsify e implementar ele na nossa pagina do GitHub.

Tarefas:

- [x] Estudar Docsify

- [x]  Implementar no GitHub Page.

- [x] Atualiza-lo com os documentos do projeto.
 
Critérios de aceitação: 

- O Docsify deve estar bem implementado.
- GitHub Page deve estar atualizado com as novas informações.

**Comment by DaviMatheus** [comment]
Trocamos o Mkdos por Docsify por causa da facilidade e da aula de monitoria, facilitando o estudo e a instalação do mesmo.

**Comment by DaviMatheus** [comment]
Atualizamos a github page com todos os documentos até agr, quando terminamos de atualizar os outros colocaremos no github page, coloquei a issue para review @antoniotoineto  @art1505  @juninhigh  depois comentem oq acharam.

**Comment by NilvanPeres** [comment]
Além de ser melhor foi mais tranquilo graças a monitoria, parabéns aos envolvidos por organizar nossa wiki.
