### ISSUE TITLE
Atualização do documento de arquitetura

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#31]
### Descrição:
Atualização do documento de arquitetura com adição de conteúdo. 
### Tarefas:

- [x] Estudar sobre a visão.
- [x] Adição de conteúdo.

### Critério de aceitação:
A issue será confirmada caso o conteúdo adicionado estiver bem contextualizado com o que a atualização do documento indicar.

**Comment by NilvanPeres** [comment]
Lembrando que o link para editarem simultaneamente está [aqui](https://docs.google.com/document/d/1cfI5MBjWi99CLA7mJtjtJ3sZp1-Umyiy04fpQLYIhTw/edit?usp=sharing). E arquivo MarkDown do documento está [aqui](https://github.com/fga-eps-mds/MDS-2020-2-G7/blob/main/docs/Documento_de_Arquitetura.md).

**Comment by NilvanPeres** [comment]
Versão inicial do Documento de Arquitetura foi adicionado. Só que os diagramas mostraram pra gente que ainda não estamos sabendo de todos os detalhes que envolvem o projeto, documento será melhorado na próxima sprint.
