### ISSUE TITLE
Elaboração do Canva do Produto

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#33]
### Descrição: 
Elaboração do Canvas do Produto

### Tarefas: 

- [x] Estudo e Aperfeiçoamento da ferramenta

- [x] Criação do Canvas

### Critérios de aceitação:

* Aprovação da equipe
* Atualizada no GitHub Pages

**Comment by DaviMatheus** [comment]
Eai glr para caso alguém tenha algum interesse em mexer com o canvas para elaboração de projetos e negocios achei uma pagina da [Sebrae]( https://www.sebrae.com.br/sites/PortalSebrae/ufs/mt/artigos/canvas-como-estruturar-seu-modelo-de-negocio,6a5cc221fcc3a510VgnVCM1000004c00210aRCRD) falando sobre. Eu tambem achei uns videos todos com mais ou menos 10 minutos, vou deixar elas enumerados na  ordem que eu mais gostei.
[1](https://www.youtube.com/watch?v=otov7o9byUk)
[2](https://www.youtube.com/watch?v=3zie3De4jKA)
[3](https://www.youtube.com/watch?v=gTLMz8mz4nQ)
[4](https://www.youtube.com/watch?v=Bk42P29eKjQ)

**Comment by DaviMatheus** [comment]
eai glr, adicionei o canvas do projeto, fiquei com duvida em relação aos cliente, caso alguém queira dar uma dica  ficarei grato.

**Comment by NilvanPeres** [comment]
Gostei do design @DaviMatheus. No momento, não tenho nada a acrescentar. Mas, possivelmente no futuro iremos acrescentar mais alguns detalhes ao canvas do projeto.
