### ISSUE TITLE
Docs sprint 03

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#35]
### Descrição:
Criar o documento da sprint 3.

### Tarefas:

- [x] Criação do planning da sprint 3.
- [x] Criação do review da sprint 3.

### Critérios de aceitação:

- O planning deve ter boa descrição do que deve ser seguido ao longo da sprint.
- A review deve ter o relato do ScrumMaster e BurnDown Chart

**Comment by NilvanPeres** [comment]
@art1505 está faltando a issue que foi criada na daily de segunda, dps da uma atualizada no doc dnv.

**Comment by art1505** [comment]
Atualizado! :)
