### ISSUE TITLE
Elaboração EAP

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#36]
### Descrição 
Criação da Estrutura Análitica do Projeto.

### Tarefas
- [x] Estudar e definir modelo de EAP do projeto.
- [x] Criação do modelo.

### Critérios de aceitação
* Diagrama do fluxograma das releases.
* Correção de ortografia.

**Comment by NilvanPeres** [comment]
Eu encontrei um site muito bom sobre o documento de Estrutura Análitica do Projeto (EAP), que pode ser encontrado [aqui](https://www.euax.com.br/2018/12/eap-estrutura-analitica-projeto/). Decidi optar pela estrutura de EAP baseada por entregas por avaliar como melhor opção para o nosso projeto. 
Outro vídeo curto e muito esclarecedor pode ser encontrado [aqui](https://www.youtube.com/watch?v=Cpffygavkx4&ab_channel=PabloCoelhoFerreira). Os níveis são bem explicados, e todos as regras para criação dos nó pai e filhos.

**Comment by NilvanPeres** [comment]
Documento adicionando ao repositório, estará em review até o Canvas do Produto ser desenvolvida pelo @DaviMatheus

**Comment by DaviMatheus** [comment]
Tranquilo, eu ja estou terminando o Canva, amanha já estará pronto

**Comment by DaviMatheus** [comment]
terminei o canvas @juninhigh  poderá utilizar ele agr

**Comment by NilvanPeres** [comment]
> terminei o canvas @juninhigh poderá utilizar ele agr

Devidamente atualizado, vou fechar a issue.
