### ISSUE TITLE
Implementação do Docker

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#37]
### Tarefas
- [x] Continuação do estudo e da config. inicial (#15) 
- [x] Implementação do Docker no projeto

### Critérios de aceitação

* Implementação revisada e aceitada pelo grupo.

**Comment by NilvanPeres** [comment]
Depois de ter  penado na #15 , consegui aprender e realizar a config inicial docker para o back-end, é bem simples, mas por ter sido o primeiro contato com a ferramenta surgiram algumas dúvidas. Basicamente segui esse [link](https://docs.docker.com/compose/django/). Tive q realizar algumas mudanças no docker-compose.yml e adiconar um arquivo startup.ssh para subir o containner para pasta SRC.

**Comment by NilvanPeres** [comment]
Aparentemente tudo certo nesse momento. A noite o grupo realizará uma call a darei instruções para todos conseguirem subir o containner na máquina.
<a href="https://ibb.co/pvbbCLk"><img src="https://i.ibb.co/wNBBDz2/docker.png" alt="docker" border="0"></a>

**Comment by fernandes-natanael** [comment]
God God

**Comment by DaviMatheus** [comment]
Estarei esperando por uma boa aula 🤓 ☝️

**Comment by Abraao1231** [comment]
agr eu aprendo docker kkkkkkkkk

**Comment by DaviMatheus** [comment]
Boa Aula, aprendi muito  :neckbeard:

**Comment by fernandes-natanael** [comment]
aula top em! nerd_face point_up

**Comment by fernandes-natanael** [comment]
aula top em! :nerd_face: :point_up:
