### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#38]
### Descrição:
Criação do protótipo de baixa fidelidade.
### Tarefas:

- [x] Estudar e definir protótipo de baixa fidelidade do projeto
- [x] Criação do documento

### Critério de aceitação:
- estar coerente com modelos passados de outros projetos

**Comment by antoniotoineto** [comment]
Decidimos adicionar o @fernandes-natanael na Issue, pois vai nos ajudar muito 👍

**Comment by antoniotoineto** [comment]
Eu e o @fernandes-natanael fizemos uma parte do protótipo de baixa fidelidade 😄  

@Abraao1231 @juninhigh @DaviMatheus @art1505 @mibasFerraz Deêm uma olhadinha e mandem seus feedbacks 👍

**Comment by NilvanPeres** [comment]
Achei massa, talvez após a reunião com a @RochaCarla, algumas métricas de consulta com os pacientes mudem. Vou mover a issue para review.

**Comment by mibasFerraz** [comment]
Ficou legal e cumpriu muito bem o papel de um protótipo de baixa fidelidade.

**Comment by fernandes-natanael** [comment]
Pessoal oque vcs acham do novo modelo de baixa fidelidade

![CadastroGestor](https://user-images.githubusercontent.com/56640659/109891753-65b90780-7c68-11eb-9b5c-c5ae06f80458.png)
![CadastroPaciente](https://user-images.githubusercontent.com/56640659/109891757-66ea3480-7c68-11eb-8db3-5f5a9eca8743.png)
![CadastroPsicologo](https://user-images.githubusercontent.com/56640659/109891761-681b6180-7c68-11eb-9a19-af9e0a2efa66.png)

**Comment by DaviMatheus** [comment]
AMMMMEIIIII 🤯

**Comment by fernandes-natanael** [comment]
Como tivemos algumas reclamacoes fiz algums outros templates 

![CadastroPaciente (2)](https://user-images.githubusercontent.com/56640659/109897324-4d011f80-7c71-11eb-83c4-58c0d80bb33d.png)
![CadastroPaciente (1)](https://user-images.githubusercontent.com/56640659/109897335-5094a680-7c71-11eb-8a7d-a96853105096.png)
![CadastroPaciente](https://user-images.githubusercontent.com/56640659/109897345-568a8780-7c71-11eb-8fd4-cc77c05a3400.png)

**Comment by fernandes-natanael** [comment]
Comentem qual vcs preferem

**Comment by DaviMatheus** [comment]
eu, preferi o branco

**Comment by art1505** [comment]
Também gostei do branco.
Brabos demais, Natana e Tonhão!!! 😮👏🏼

**Comment by antoniotoineto** [comment]
Prefiro o todo branco também 👏 bom trabalho

**Comment by fernandes-natanael** [comment]
como ainda n definimos como o produto vai funcionar tentamos criar uma ideia de como vai funcionar o produto:

***Ausencia de acento pq eu to com sono.***

## como funciona sistema de cadastro:
- Na pagina inicial o gestor ou psicologo que quer participar do sistema Cheery up seleciona o botao solicitar cadastro.
- dai ele preenche os dados dele e envia para o admin.
- o admin recebe uma mensagem no perfil dele e aceita ou rejeito os dados.
- Caso aceito o admin cadastra o psicologo ou gestor.
- Em seguida  o admin manda por email uma senha aleatoria pro usuario, que podera ser alterada depois.
- O psicologo/gestor podera acessar sua conta indo em login.



## Tela de inicio

![Tela de inicial](https://user-images.githubusercontent.com/56640659/109912780-834b9880-7c8b-11eb-8af1-34ea1457ffc4.png)

## Perfil Admin

![Perfil admin](https://user-images.githubusercontent.com/56640659/109912790-86df1f80-7c8b-11eb-8321-773e98a44bd1.png)

## Perfil Psicologo

![Perfil Psicologo](https://user-images.githubusercontent.com/56640659/109912796-89da1000-7c8b-11eb-8500-9a8ae3fa5495.png)

## Perfil Gestor

![Perfil Gestor](https://user-images.githubusercontent.com/56640659/109912801-8c3c6a00-7c8b-11eb-80c6-4f5e184f1d4e.png)

## Perfil Paciente

![Perfil paciente](https://user-images.githubusercontent.com/56640659/109912805-8e062d80-7c8b-11eb-9927-6360d8da32f9.png)

**Comment by antoniotoineto** [comment]
## Complementação de imagens pra explicação do @fernandes-natanael 👍 
## Solicitação de Cadastro
![Solicitar Cadastro](https://user-images.githubusercontent.com/54555684/109913600-0b7e6d80-7c8d-11eb-9c67-1ed1a90a8233.png)
## Solicitação de Cadastro - Psicólogo
![Solicitar Cadastro - Psicologo](https://user-images.githubusercontent.com/54555684/109913602-0de0c780-7c8d-11eb-942e-95e2896b06d4.png)
## Solicitação de Cadastro - Gestor
![Solicitar Cadastro  - Gestor](https://user-images.githubusercontent.com/54555684/109913578-04eff600-7c8d-11eb-85ef-c262e6f0e03d.png)
## Tela de Login
![TelaDeLogin](https://user-images.githubusercontent.com/54555684/109913590-091c1380-7c8d-11eb-8d2c-79fe5d4dda0f.png)

**Comment by NilvanPeres** [comment]
Capricharam demais, parabéns @fernandes-natanael @antoniotoineto. Pro prótipo de alta vai restar só mudar o estilo kkkkk

**Comment by gabrielapivetta** [comment]
Meu deus!!! Artistas, ta lindo demais, vocês são meu orgulho!

**Comment by Abraao1231** [comment]
ficou excelente, conseguiram dar mais atenção as informações certas @fernandes-natanael .

**Comment by fernandes-natanael** [comment]
Valei galera, depois da reunião que tivemos com a professora, vou reduzir apenas para as páginas que serão feitas por nos e mando mais tarde aqui dnv
