### ISSUE TITLE
Construção do Product Backlog

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2020.2-CheeryUP#39]
### Descrição:
Para uma evolução do projeto, discutiremos o backlog do produto.
### Tarefas:

- [x] Discutir e organizar o backlog do produto.
- [x] Publicar o backlog do produto.

### Critério de aceitação:
- Seguir os padrões propostos pelo tema da professora;
- Time estar de acordo com o Product Backlog.

**Comment by DaviMatheus** [comment]
Eai, glr eu e o @fernandes-natanael terminas de construir o primeiro prototipo do backlog, temos algumas duvidas em relação ao escopo do projeto em si, gostaria da revisão de vcs.

**Comment by NilvanPeres** [comment]
Gostei dos pontos levantados, também tenho dúvida se devemos dar algum tipo de acesso aos pacientes no site. Acredito que após uma reunião com a @RochaCarla, iremos validar o escopo do projeto e sanar algumas dúvidas sobre as funcionaldidades que serão oferecidas.
@DaviMatheus  e @fernandes-natanael acredito que eu como, psicólogo, gostaria ver de quadro de evolução de determinado paciente.

**Comment by antoniotoineto** [comment]
Muito bom ver o projeto começando a criar vida!! Li o backlog do projeto e também queria acrescentar alguns detalhes como:
* Os pacientes terem acesso ao feedback de outros pacientes, talvez? 
 
Podemos acertar tudo na próxima reunião. Belo trabalho @fernandes-natanael @DaviMatheus 👏
