### ISSUE TITLE
Estudar GitHub

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#4]
- [x] Assistir aula da quinta-feira com os monitores.

- [x] Pesquisar matérias complementares e informações para o aprendizado do GitHub.

- [x] Entender os Conceitos e ferramentas básicas do GitHub para o trabalho em conjunto do grupo.

**Comment by Abraao1231** [comment]
Foram pesquisados os conceitos básicos de git e github para um melhor desenvolvimento e eficiência na elaboração do projeto entre eles estão os comandos de terminal do git para a configuração e reparos do projeto.

Foi visto como extensões do vscode pode ser útil para uma melhor visualização do seu repositório com extensões como o gitlens.

**Comment by Abraao1231** [comment]
Video explicando sobre os comandos do git [Link](https://youtu.be/2alg7MQ6_sI) da rocketseat

**Comment by art1505** [comment]
Pequeno resumo a respeito do github e seus comandos mais básicos:

* O que é Github ?

  Plataforma responsável pela hospedagem de código-fonte e arquivos com controle de versão usando o Git. Tem, portanto, um papel importante no processo de gerenciamento de projetos  e versões de código, além de ser uma importante plataforma de rede social para os desenvolvedores.
   O GitHub é uma excelente ferramenta para o trabalho em equipe. Quando se trata de um software ou um site que precisa ser criado em conjunto, por exemplo, a plataforma online facilita, sem dúvidas, a gestão do projeto. Através dele é possível, portanto, que haja contribuição simultânea do participantes do projeto, editando e criando novos arquivos e permitindo que os mesmos possam existir sem o risco de suas alterações serem sobrescritas.

* Matérias complementares sobre comandos básicos do Github:

https://gist.github.com/leocomelli/2545add34e4fec21ec16 : importante guia com comandos que serão, certamente, usados ao longo do projeto. Além disso, especifica o contexto em que melhor se encaixam comandos de funções parecidas.

https://rogerdudler.github.io/git-guide/index.pt_BR.html: apesar de uma riqueza de informações menor do que o link anterior (pelo menos em questão de quantidade de comandos), apresenta uma boa explicação sobre cada comando.

https://www.hostinger.com.br/tutoriais/comandos-basicos-de-git/: também possui uma boa quantidade de comandos e explicação para cada um deles. 

https://dev.to/womakerscode/git-e-github-guia-rapido-e-comandos-basicos-para-iniciantes-4ile: colocando mais esse porque possui informações importantes (com riqueza visual) que podem ser importantes aos iniciantes.

**Comment by Abraao1231** [comment]
# Estudo e pesquisa de conceitos, ferramentas para Git e Github

## Conceito básico
Git e Github são ferramentas para ajudar no melhor desempenho e organização de um projeto em equipe simultaneamente, onde o Git seria a parte remota onde apenas o desenvolvedor que está utilizando faz as devidas alterações no projeto e depois o manda para o github, que é a parte onde seu projeto fica salvo na nuvem e disponível para os outros integrantes da equipe.

## Comandos Git

### 1. Configurar git
`git confuser.nameig --global  "seu nome"`
` git config --global user.email "seu email"`		

### 2. Criar repositório
`git init`
### 3. Clonar repositório da nuvem

`git clone https://github.com/<usuario>/site.git `
	   
### 4. Adicionar arquivo ao repositório(Local)

- **4.1 Adicionar arquivo**
         `git add "arquivo"`
- **4.2 Criar commit**
	`git commit -m "mensagem"`
- **4.3 Exibir commits**
	`git log`
		
### 5 Subir arquivos para o github
`git push`
### 6 Trazer modificações do github para o repositório local
  `git pull`
### 7- Branch

-   7.1 - Criar nova branch no repositorio(local)  
                `git branch "nome da branch"`
-   7.2 Mudar de branch  
               `git checkout " Nome da branch"`
-   7.3 Deletar branch  
              `git branch -d "nome da branch`
