### ISSUE TITLE
Construção do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2020.2-CheeryUP#40]
### Descrição:
Inicialização do protótipo de alta fidelidade.

### Tarefas:

- [x] Aprimoração do modelo da aplicação web a partir do protótipo de baixa fidelidade.
- [x] Adição do protótipo no projeto.

### Critério de aceitação:
- estar coerente com o escopo do projeto.

**Comment by antoniotoineto** [comment]
Protótipo de alta fidelidade sofreu algumas mudanças em relação ao de baixa fidelidade, referente à retirada de algumas funcionalidades... mas jaja tá pronta 


![1575210456_2](https://user-images.githubusercontent.com/54555684/110831894-77f30100-8279-11eb-8d63-9927f694b05e.gif)

**Comment by antoniotoineto** [comment]
Protótipo de Alta fidelidade adicionado [aqui](https://github.com/fga-eps-mds/2020.2-CheeryUP/tree/main/docs/Prot%C3%B3tipos/Alta%20fidelidade) 👍 
Issue será fechada #40
