### ISSUE TITLE
Atualizações do GitHub Pages e do documento de Arquitetura

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#41]
### Descrição:
Atualizações dos docs no GitHub Pages e aprofundamento dos tópicos dentro do documento de Arquitetura.

### Tarefas:
- [x] Aprimoração do documento de arquitetura.
- [x] Atualização do GitHub Pages.

### Critério de aceitação:
- Documentos estarem corretos.

**Comment by Abraao1231** [comment]
Foi atualizado o diagrama de casos de uso de acordo com o o que foi visto em reunião.

**Comment by fernandes-natanael** [comment]
atualizei o DER e alguns atributos do MER que o @antoniotoineto n tinha colocado, vou fechar a Issue
