### ISSUE TITLE
Templates pasta .gitub

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#42]
### Descrição:
Criação da pasta .github para templates de issues e PR's.  #20
### Tarefas:

- [x] Procurar bons modelo e adaptar para o uso do nosso projeto.
- [x] Criação dos templates na pasta .github

### Critério de aceitação:
* O template de issues deve ter uma pasta com os tipos de issues essenciais que serão usados ao longo do projeto.

**Comment by NilvanPeres** [comment]
Colocada as issues principais. Galera, @art1505  @fernandes-natanael @DaviMatheus @antoniotoineto @Abraao1231, caso vocês julguem necessário a criação de um novo template de issue, fiquem á vontade.

**Comment by NilvanPeres** [comment]
Lembrando que utilizei como base a [BOSS](https://github.com/BOSS-BigOpenSourceSister/BigSister/tree/main/.github/ISSUE_TEMPLATE) e a [Acacia](https://github.com/fga-eps-mds/2019.2-Acacia/tree/develop/.github).

**Comment by DaviMatheus** [comment]
Para mim ficou bom, caso eu tenha alguma outra ideia ou eu veja outro repositório com uma issue boa eu falo com vcs 😄

**Comment by antoniotoineto** [comment]
Templates ótimos 👍 Vamos nos atentar de seguir esse padrão daqui em diante.
Numa próxima reunião verificaremos se é preciso adicionar algo mais.

**Comment by art1505** [comment]
Dois outros templates adicionados . Um deles, referente ao "docs", possui apenas tópicos que nortearão a decisão de adição, alteração ou remoção de arquivos da pasta. 👍 -_- 👍

**Comment by antoniotoineto** [comment]
Fiz uma adição no template de ATAs @juninhigh, depois confere lá 🙈
