### ISSUE TITLE
Identidade visual do projeto

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#43]
###  Descrição
Adicionar nome e Logo do projeto, e organizar e linkar novo repositório para o front-end.

### Tarefas

- [x] Adicionar o nome e logo do projeto no repositório
- [x] Criação do repositório para o front-end do projeto.
- [x] Atualização inicial do readme

### Critérios de aceitação
* Todos devem estar de acordo com o nome e logo escolhidos.

**Comment by NilvanPeres** [comment]
A mente criativa do grupo, vulgo @antoniotoineto propôs dois nomes para o projeto.

1. MindUP
2. CheeryUP

O primeiro foi descartado por já existir uma marca de roupa e um site com esse mesmo nome.
O CheeryUP, seria um trocadilho de como o paciente sairia da consulta com o psicólogo, ou seja, de um estado ruim para um estado mais alegre 😃. A palavra por ser bem parecida com Cherry, tb ajudaria para colocar um cereja como  a "mente" do paciente.

![](https://media1.giphy.com/media/kaq6GnxDlJaBq/giphy.gif)

**Comment by antoniotoineto** [comment]
_Cheery Up_ será um bom nome 😃  
Atenderá bem à ideia do projeto, além de uma cerejinha enfeitando nosso logo 🍒

**Comment by NilvanPeres** [comment]
Nosso back-end mais front-end que tem, vulgo @fernandes-natanael. Propôs alguns logos como:
<a href="https://ibb.co/Zm0Fdhw"><img src="https://i.ibb.co/ySrZ08M/natanael.jpg" alt="natanael" border="0"></a>

O logo que está na frente, segundo a  boca de urna é esse aqui:
<a href="https://ibb.co/hMBk3L6"><img src="https://i.ibb.co/26vwGW9/cereja.jpg" alt="cereja" border="0"></a>

**Comment by fernandes-natanael** [comment]
Gostei do nome que o @antoniotoineto pensou. Estou tentando usar minha criatividade  pra ficar igual o Thomas Shelby do Pick Brauliu.

**Comment by NilvanPeres** [comment]
Apuração dos votos sairam, cobertura ao vivo [aqui](https://doodle.com/poll/ebh3zm6b7usyfzy9?utm_source=poll&utm_medium=link). Aparentemente a boca de urna deu errado , e teve margem de erro 50% para cima ou para baixo.
![](https://media.giphy.com/media/111ebonMs90YLu/giphy.gif)

**Comment by NilvanPeres** [comment]
Link do repositório do front https://github.com/fga-eps-mds/2020.2-CheeryUP-FrontEnd . Todos já estão adicionados, vou fechar a issue.
