### ISSUE TITLE
Atualização de documentos em geral

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#46]
### Descrição:
Atualização de todos os documentos do repositório.
### Tarefas:

- [x] Atualizar RoadMaps.
- [x] Atualizar gh-pages.
- [x] Atualizar TAP, e Documento de Visão e outros.

### Critério de aceitação:
Todos os membros devem contribuir nesses consertos.

**Comment by NilvanPeres** [comment]
Arrumei o link dos sumários nos documentos: Visão, Arquitetura e TAP. E inserida a atualização do RoadMap do ScrumMaster.

**Comment by NilvanPeres** [comment]
@mibasFerraz  @DaviMatheus  @antoniotoineto @Abraao1231  @art1505 @fernandes-natanael Acredito que a parte da referência dos documentos precisa ser complementada. No documento de Arquitetura, falta complementar sobre o MVT.

**Comment by DaviMatheus** [comment]
Atualização do Docs feita com sucesso.
