### ISSUE TITLE
Estudo  linguagem/frameworks back-end

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#47]
### Descrição:
Estudo das tecnologias de desenolvimento do back-end.
### Tarefas:

- [x] Estudar Python e Django
- [x] Implementar classe psicólogo.

### Critério de aceitação:
- Compartilhamento de aprendizagem, podendo ser via: disponibilização de materiais úteis ou rachando algum curso.
- Treinamento dos que possuem mais conhecimento em python com os integrantes que nunca tiveram contato com a linguagem.

**Comment by NilvanPeres** [comment]
Salve galera do back-end. Passando aqui pra recomendar essa playlist de Django+React (pensando nos endpoints do back), ela pode ser encontrada [aqui](https://www.youtube.com/playlist?list=PLzMcBGfZo4-kCLWnGmK0jUBmGLaJxvi4j).

**Comment by DaviMatheus** [comment]
vlw pela dica @juninhigh, darei uma olhada

Também achei uma playlist que eu já tinha começado a aprender e eu achei muito fácil, o [link](https://www.youtube.com/watch?v=UmljXZIypDc&list=RDCMUCCezIgC97PvUuR4_gbFUs5g&start_radio=1&t=494s) , e outro que eu ja fiz o curso e pra quem é bem iniciante e quer aprender em um dia o curso completo de 4 horas para [django](https://www.youtube.com/watch?v=F5mRW0jo-U4)

pessoalmente eu gostei mais do primeiro link. @fernandes-natanael  @Abraao1231  @mibasFerraz

**Comment by mibasFerraz** [comment]
Show, galera. Vou botar aqui uma introdução breve e uns canais legais que achei também

### O que é o Python?

Python é uma linguagem de programação de alto nível, dinâmica, interpretada, modular, multiplataforma e orientada a objetos - uma forma específica de organizar softwares onde, a grosso modo, os procedimentos estão submetidos às classes, o que possibilita maior controle e estabilidade de códigos para projetos de grandes proporções.


### Instalação e vídeo aulas
Uma opção mais completa e em português pode ser encontrada no [curso em vídeo](https://youtu.be/S9uPNppGsGo)
Uma opção mais curta e em inglês pode ser encontrada no [programingKnowledge](https://www.youtube.com/watch?v=rVb1TqqbPj0)

### Fontes:
https://kenzie.com.br/blog/o-que-e-python/

**Comment by mibasFerraz** [comment]
### O que é o Django?

Django é um framework para aplicações web gratuito e de código aberto, escrito em Python. Um web framework é um conjunto de componentes que ajuda você a desenvolver sites de forma mais rápida e fácil. Um vídeo explicativo pode ser visto no [Código fonte TV](https://www.youtube.com/watch?v=ao8pCrRqKOs)

### Instalação e vídeo aulas
Uma opção em português com duração de 1h30min pode ser encontrada no [Fabio Ruicci](https://www.youtube.com/watch?v=Dzuiy-JNi-E)
Uma opção em inglês com duração de 3h40min pode ser encontrada no [freeCodeCamp.org](https://www.youtube.com/watch?v=F5mRW0jo-U4)

### Fontes:
https://tutorial.djangogirls.org/pt/django/

**Comment by Abraao1231** [comment]
achei uma playlist de aulas no youtube sobre como funciona um server django exemplificando fazendo um pequeno projeto recomendo muito [Playlist](https://www.youtube.com/watch?v=UIvnNCQnejw&list=PLHWfNMxB2F4HdKbo8zdgXyxVDOxH429Ko)

**Comment by DaviMatheus** [comment]
https://www.djangoproject.com/start/ o monitor nos recomendou ler a documentação inteira do django dizendo : "a documentação é melhor que qualquer tutorial do youtube, por que é feita pela comunidade, e a comunidade sabe o q faz"
