### ISSUE TITLE
Estudo Heroku 

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#48]
### Descrição:
Estudo e resumo da plataforma em nuvem Heroku para os colegas
### Tarefas:

- [x] Estudo da plataforma
- [x] Resumo e documentação.

### Critério de aceitação:
Todos os integrantes entenderem o funcionamento e a importância para o projeto

**Comment by DaviMatheus** [comment]
# HEROKU

### O que é Heroku?

- Heroku é uma plataforma em nuvem como um serviço que suporta várias linguagens de programação, que faz deploy de várias aplicações back-end seja para hospedagem, testes em produção ou escalar as suas aplicações. Também tem integração com o GitHub, deixando o uso mais fácil e com containers denominados Dyno. O Heroku possui uma versão gratuita e oferece versão de teste grátis. Versão paga do Heroku a partir de US$ 7,00/mês.

<p align = "center"> &emsp;&emsp; <img src="https://image.flaticon.com/icons/png/512/873/873120.png" width="200" height="200"/> </p>

### Para que serve o Heroku ?

- O Heroku é uma plataforma como serviço (Paas) na nuvem baseada em contêiner. Os desenvolvedores usam o Heroku para implantar, gerenciar e dimensionar aplicativos modernos. A plataforma é flexível e fácil de usar, oferecendo um caminho mais simples para levar os aplicativos ao mercado. O Heroku é gerenciado, dando aos desenvolvedores a liberdade de focar no produto principal sem o ônus de manter a infraestrutura do aplicativo. Ferramentas, serviços e fluxos de trabalho integrados são meticulosamente projetados para ajudar a maximizar a produtividade individual e da equipe.

## Como instalar

- Eu achei um site explicando muito bem como baixar e dar seu primeiro deploy, podendo ser acessado [aqui](https://share.atelie.software/subindo-um-site-simples-para-o-heroku-7450592106c8) 
 -E [aqui](https://devcenter.heroku.com/articles/heroku-cli)  está como instalar para qualquer S.O 

### VIDEOS E LINKS

- Caso vcs queiram eu vou deixar uma serie de links e videos que são importantes para ter um entendimento básico de Heroku

## Introdução 

1 - esse [video](https://www.youtube.com/watch?v=aUW5GAFhu6s) é um video curtinho de 4 minutos só para entender na pratica o heruko, caso voce queira aprofundar no assunto, sugiro esse video [aqui](https://www.youtube.com/watch?v=QTOkqzCTGxw) 

## Django 

2- Nesse [video](https://www.youtube.com/watch?v=kBwhtEIXGII) ele  faz o deploy no Heruko usando o Django como back-end, então poderia ser usada como base para nós

## Docker

3- Nesses ultimos dois videos eles utilizaram o Docker, [video mais longo](https://www.youtube.com/watch?v=4axmcEZTE7M)
[video mais curto](https://www.youtube.com/watch?v=tTwGdUTR5h8)


##### Fontes: 

https://adamatti.github.io/blog/git/2017/06/04/heroku.html
https://share.atelie.software/subindo-um-site-simples-para-o-heroku-7450592106c8
https://devcenter.heroku.com/articles/heroku-cli

**Comment by NilvanPeres** [comment]
Tudo certo na instalação do Heroku aqui @DaviMatheus. Gostei bastante dos vídeos que você selecionou, consegui ver os curtos só faltas os mais longos para dar uma aprofundada na ferramenta.
