### ISSUE TITLE
Escolha de Temas do projeto

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#5]
- [x] Escolha de 3 temas para a elaboração do projeto

**Comment by NilvanPeres** [comment]
Os temas propostos por mim são:

1. Prontuário eletrônico no contexto de covid. (Professora)
2. Fazer um app/página web que compara os preços de remédios de farmácias próximas ao usuário. (alá buscapé)
3. Criar um app de alerta para motoristas de uber/pop/cabify, etc. O app alertaria regiões em que ocorrem um número muito alto de  roubo de carros, para os mesmos evitarem tal percursos. Além de funcionalidades para garatir mais segurança ao condutor, como um chamado simples de SOS.   **dados ???**
4. Criar um app/página web para auxiliar produtores de leite, indicando: os latícinios que estão pagando os melhores preços, qual a média do preço do leite no mês por estado, se a qualidade de CSS e CBT forem boas propor um "match" entre produtor e laticínio mais "fortes". **dados??**
5. Projeto de monitoramento de contratos da UnB. (Professora)

**Comment by fernandes-natanael** [comment]
1. Um app/pagina web, onde pode-se acompanhar o estoque de uma transportadora de matérias de construção.
2. Um app em que conecta diretamente uma pessoa que quer reciclar um determinado matéria diretamente com as empresas que reciclam tal matérial.

**Comment by DaviMatheus** [comment]
1- Fazer um app/página web para ajudar aqueles que possui um hobby para jardinagem ou para facilitar quem quer começar, mostrando um catalogo de plantas, onde ela vai poder personalizar, procurando as mais fáceis de cuidar ate as mais difíceis, o preço delas, buscando  onde é mais barato comprar, o adubo, o tempo que ela precisa ficar no sol e na sombra, a quantidade de água necessária e etc, podendo até dar dicas e sugestões de proximas compras de planta parecidas ou totalmente diferentes para a pessoa experimentar.

2. Um app/ pagina web que ajude os ambulantes, comerciantes, panfletagens mostrando onde possui mais circulo de pessoas naquela região(atualizando a cada dia da semana), baseados em dados adquiridos pelas semanas, ou meses, para eles poderem colocar suas mercadorias/ marketings em lugares públicos é claro. Esse app/ pagina pode até sugerir mercadorias que são mais aceitas pelo publico daquela região/ também pode mostrar horários e locais mais seguros para diminuir o aumento de roubo e entre outras funcionalidades

**Comment by Abraao1231** [comment]
1 - criar um app/web onde possa ser realizado o cadastro e reserva de áreas esportivos do Centro Olímpico da Unb, mostrando áreas, quadras, piscinas, salões, equipamentos e etc. que podem ser reservados para uma determinada atividade.

2- criar um App/ pagina web onde seja possível monitorar monitorar o desempenho e desenvolvimento de uma criança na escola analisando dados enviados pelos professores, coordenadores etc.

**Comment by art1505** [comment]
1- Criar um app/web que informe oficinas mecânicas mais próximas a um eventual problema. Entre as informações iniciais concedidas, estão: endereço, telefone e horários de funcionamento.
Ao clicar na opção desejada, o cliente vai ter acesso a uma relação de peças ou produtos em estoque e falta.

2- Criar um app/web com o objetivo de proporcionar uma maior interação entre os alunos do Campus, onde alunos de todos os semestres poderão interagir entre si diariamente. Tais interações se tratam de tópicos que vão desde perguntas relacionadas à Universidade até conversas casuais.
Ao clicar em um tópico, o aluno é direcionado a um chat com aquele tema.
O intuito é que pessoas se ajudem em um ambiente onde a ansiedade e outros muitos problemas podem se intensificar. 
Apesar disso, é quase inevitável a presença de pessoas com más intenções. Assim, se faz necessário que cada chat possua uma opção de denúncia ao participante que tenha eventualmente ingressado para atrapalhar. A denúncia é analisada pelos organizadores e, se condizente, é enviada aos superiores, podendo gerar as punições que julgarem necessárias.

**Comment by antoniotoineto** [comment]
1- Criar um app/web que auxilia o usuário à manter uma rotina melhor, mais produtiva e mais saudável. O projeto consiste em um app/web que mostra quanto tempo o usuário estudou, comeu, dormiu, fez exercício físico ou praticou atividade de lazer ao longo do dia. Todas essas informações seriam colocadas pelo usuário ao passar do dia, e por fim, o indivíduo fosse capaz de ter um melhor controle de sua rotina, podendo melhorar ou mantê-la ao longo do tempo.
2-  Criar um app/web que mostra ao usuário informações sobre um determinado medicamento/remédio, ajudando-o de forma prática e rápida o indivíduo à saber se ele deve ou não usar este medicamento/remédio, de acordo com sua função e contra-indicações.

**Comment by NilvanPeres** [comment]
Os temas escolhidos pelo grupo foram : 
1 - Prontuário eletrônico no contexto de covid.
2 - App/web para jardinagem. Proposto por : @DaviMatheus 
3 - App/web para reciclagem. Proposto por : @fernandes-natanael
