### ISSUE TITLE
Aplicação das Tabelas do Banco de Dados 

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#50]
### Descrição:
Começando a implementação do banco de dados, começando no estudo e aplicação das tabela
### Tarefas:

- [x] Estudo da funcionalidade do Banco de Dados 
- [x] Pensar e Aplicar as tabelas.

### Critério de aceitação:
Treinamento de Banco de Dados, e o aprendizado de suas aplicações

**Comment by fernandes-natanael** [comment]
## Entre parenteses sao os atributos das indentidades

### Tabela Psicologo
create table psicologo(
	id serial PRIMARY KEY, *identificador do psicologo que se auto incrementa *
	nome varchar(90) NOT NULL, *// Defini tamanho maximo para nome e nao pode ser nulo*
	email varchar(90) NOT NULL, *// Defini tamanho maximo para email e nao pode ser nulo*
	senha varchar(15) NOT NULL, *// Defini tamanho maximo para senha e nao pode ser nulo*
	genero char(1)  NOT NULL *// genero seria um char de 1 caracter e nao pode ser nulo*
);

### Tabela Paciente
create table paciente(
	id serial PRIMARY KEY, *indentificador que se auto incrementa*
	nome varchar(90) NOT NULL, *// Defini tamanho maximo para nome e nao pode ser nulo*
	email varchar(90) , *// Defini tamanho maximo para email*
	dataNascimento Date, *// Armazenado a data de nascimento do paciente*
	situacao char(1), *// situacao de saude mental q o paciente se encontra*
	genero char(1),  *// genero um char representando 'Masculino' ou 'Femenino' ou S/N*
	regiao char(1) *// regiao de brasilia onde o paciente mora*
);
### Tabela Consutla

create table consulta(
	cod_consulta SERIAL PRIMARY KEY, *// Indentificador da consulta auto incrementado* 
	id_psicologo serial NOT NULL REFERENCES psicologo(id), *// Id do psicologo para saber com quem esta ocorrendo a consulta*
	id_paciente serial NOT NULL, *// id do paciente*
	data_horario TIMESTAMP WITH TIME ZONE, *// Data é horário da consulta* 	
	FOREIGN KEY (id_paciente) REFERENCES pacientes(id) 

);

## Pergunta
Eu e o @DaviMatheus fizemos aq, o que voces acham de as tabelas serem implementadas dessa forma inicialmente ?

**Comment by NilvanPeres** [comment]
Sobre as que tabelas sugeridas, concordo com todos os campos, acho que abrange tudo que é importante para o projeto. Mas tenho uma pergunta, nesse primeiro momento, teria alguma tabela para o quadro evolutivo dos pacientes ? @DaviMatheus  @fernandes-natanael

**Comment by fernandes-natanael** [comment]
create table psicologo(
	id serial PRIMARY KEY, 
	nome varchar(90) NOT NULL,
	email varchar(90) NOT NULL,
	senha varchar(15) NOT NULL, 
	genero char(1)  NOT NULL 
);

create table paciente(
	id serial PRIMARY KEY, 
	nome varchar(90) NOT NULL, 
	email varchar(90) , 
	dataNascimento Date, 
	situacao char(1), 
	genero char(1),  
	regiao char(1) 
);

create table consulta(
	cod_consulta SERIAL PRIMARY KEY, 
	id_psicologo serial NOT NULL REFERENCES psicologo(id),
	id_paciente serial NOT NULL, 
	data_horario TIMESTAMP WITH TIME ZONE, 	
	FOREIGN KEY (id_paciente) REFERENCES pacientes(id) 

);

**Comment by DaviMatheus** [comment]
Ambietizamos o banco-de-dados utilizando  o djago admin 


<a href="https://ibb.co/kqLvSvB"><img src="https://i.ibb.co/ssTzVzR/Screenshot-from-2021-03-11-18-03-27.png" alt="Screenshot-from-2021-03-11-18-03-27" border="0"></a>

com isso só falta a criação de mais models, que deixaramos para a proxima sprint 😡
