### ISSUE TITLE
Feedback Sprint 4

### ISSUE THREAD

**Issue by Giuulob89** [fga-eps-mds/2020.2-CheeryUP#54]
# Feedback Geral

Oii, pessoal, meu nome é @Giuulob89 e agora também sou monitora de vocês! Eu e a @gabrielapivetta estivemos um pouco enroladas essas últimas semanas, mas voltamos aqui para dar uma atualizada sobre como está a avaliação do projeto.
Ficamos felizes em observar que não estão tendo dificuldades em se organizar e fazer o que se propõem, a documentação está muito bem feita e o repositório organizado e intuitivo, com arquivos e pastas bem explicados, além de issues bem comentadas com discussões pertinentes. No próximo tópico, observamos algumas coisinhas a mais, que achamos importante que deem uma olhada, mas saibam que estão fazendo um excelente trabalho!

# Pontos Observados

- É importante que deixem mais claro no fluxo do usuário como será a interação do paciente com o sistema (inclusive, gostaríamos que nos explicassem para que possamos avaliar melhor e ver se a documentação está feita de forma correta);

- Vimos o documento de casos de uso de vocês e cremos que a explicação dele está um pouco rasa e que faltam alguns elementos consideráveis nesse tipo de documentação. Por exemplo, se o paciente também tem interação com o sistema é necessário que isso seja explicado no diagrama e também é importante que façam as indicações de uma forma mais explicativa (existem relações diferentes entre as setas, ex: extend e include) e as relações são explicadas dentro de uma caixa que representa o sistema. Sugestão: Estudem essas relações.
- Lembrem que o projeto está com o escopo bem grande, então focar apenas nas features de prioridade alta, no primeiro momento, é essencial;
- Gostamos de ver que fizeram todas as documentações que se propuseram e que já iniciaram a primeira feature do projeto, pois, assim, sobra bastante tempo para revisões antes da R1;
- A identidade visual de vocês também está muito bem trabalhada(um arraso), parabéns!

**Comment by NilvanPeres** [comment]
Obrigado pelo feedback @Giuulob89  e @gabrielapivetta . Muito obrigado pelos pontos levantados, nós até tinhamos falado da refatoração da caso de uso hoje, vamos deixar ela bem melhor até a R1. Sobre o ponto 1 (fluxo de usuário), não entendi muito bem, poderia explicar novamente  ?

**Comment by DaviMatheus** [comment]
o fluxo do usuario dentro da pasta prototipo @juninhigh  a gente fez de um modo meio raso, eu e o natanel já estávamos pensando em especificar mas agr temos certeza kkk

**Comment by fernandes-natanael** [comment]
Vamos atualizar algumas coisas nessa semana, estamos tendo alguns problemas de comunicação sobre o projeto que precisamos corrigir está semana

**Comment by gabrielapivetta** [comment]
> Obrigado pelo feedback @Giuulob89 e @gabrielapivetta . Muito obrigado pelos pontos levantados, nós até tinhamos falado da refatoração da caso de uso hoje, vamos deixar ela bem melhor até a R1. Sobre o ponto 1 (fluxo de usuário), não entendi muito bem, poderia explicar novamente ?

Sobre o fluxo de usuário só não ficou muito claro como será a interação do paciente com o sistema, só mostra as atividades do psicólogo. Por exemplo, como o paciente vai marcar e visualizar as consultas? Do jeito que foi feito parece que só o psicólogo pode fazer login e as demais atividades.

**Comment by mibasFerraz** [comment]
A ideia que a professora passou pra gente é justamente essa. O paciente não ter nenhuma interação com o site, apenas o psicólogo.

> > Obrigado pelo feedback @Giuulob89 e @gabrielapivetta . Muito obrigado pelos pontos levantados, nós até tinhamos falado da refatoração da caso de uso hoje, vamos deixar ela bem melhor até a R1. Sobre o ponto 1 (fluxo de usuário), não entendi muito bem, poderia explicar novamente ?
> 
> Sobre o fluxo de usuário só não ficou muito claro como será a interação do paciente com o sistema, só mostra as atividades do psicólogo. Por exemplo, como o paciente vai marcar e visualizar as consultas? Do jeito que foi feito parece que só o psicólogo pode fazer login e as demais atividades.

**Comment by antoniotoineto** [comment]
Obrigado pelo Feedback @Giuulob89 e @gabrielapivetta 💯. Vamos atualizar todos os documentos de forma que fique bem claro o que no projeto consiste!! E vamos trabalhar para que o tudo fique de acordo com escopo.
