### ISSUE TITLE
Implementação dos módulos de banco de dados

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#57]
### Descrição
realizar estudo sobre a implementação do banco de dados em django para que possam ser possivel realizar o cadastro de psicólogos no futuro
### Tarefas:

- [x] Estudar os modúlos de banco de dados e django.
- [x] implementar os módulos no projeto na branch develop
### Critério de aceitação:
A issue será aceita se o pulll request for devidamente aceito.

**Comment by fernandes-natanael** [comment]
## Variaveis do tipo select
  
GENERO = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('P', 'Prefiro não responder'),
    )
    REGIAO = (
        ('AC', 'Águas Claras'),
        ('AS', 'Asa Sul'),
        ('AN', 'Asa Norte'),
        ('CI', 'Ceilândia'),
        ('GA', 'Gama'),
        ('GA', 'Guará'),
        ('RE', 'Recanto das Emas'),
        ('RF', 'Riacho Fundo'),
        ('SA', 'Samambaia'),
        ('SO', 'Sobradinho'),
        ('TA', 'Taguatinga'),
        ('EO', 'Entre outros'),
    )
    SITUACAO = (
        ('C', 'Controlada'),
        ('M', 'Moderada'),
        ('G', 'Grave'),
    )

Queria ajuda para pensar em mais opções de região, foi as que eu pensei

**Comment by fernandes-natanael** [comment]
ja atribui os modelos inicialmente dessa forma:
![Screenshot from 2021-03-12 21-06-42](https://user-images.githubusercontent.com/56640659/111011008-deaa1480-8376-11eb-8064-12941d97d209.png)

onde todos os atributos sao obrigatorios exceto a descrição.

OBS: O id_paciente é um serial que vem por default no django e não aparece ai na imagem, mas ele existe :angry:

**Comment by antoniotoineto** [comment]
> ## Variaveis do tipo select
> GENERO = (
> ('M', 'Masculino'),
> ('F', 'Feminino'),
> ('P', 'Prefiro não responder'),
> )
> REGIAO = (
> ('AC', 'Águas Claras'),
> ('AS', 'Asa Sul'),
> ('AN', 'Asa Norte'),
> ('CI', 'Ceilândia'),
> ('GA', 'Gama'),
> ('GA', 'Guará'),
> ('RE', 'Recanto das Emas'),
> ('RF', 'Riacho Fundo'),
> ('SA', 'Samambaia'),
> ('SO', 'Sobradinho'),
> ('TA', 'Taguatinga'),
> ('EO', 'Entre outros'),
> )
> SITUACAO = (
> ('C', 'Controlada'),
> ('M', 'Moderada'),
> ('G', 'Grave'),
> )
> 
> Queria ajuda para pensar em mais opções de região, foi as que eu pensei

Mais uma ideia de Região: ('AR', 'Arniqueiras')
E mais uma coisa, como vamos colocar os quadros gerais no módulo do banco de dados? Iremos fazer isso afinal?

**Comment by fernandes-natanael** [comment]
como assim quadros gerais ?

**Comment by gabrielapivetta** [comment]
Gente, essa imagem que vocês colocaram o print é uma tela da interface ou é do banco de dados?

**Comment by fernandes-natanael** [comment]
@gabrielapivetta é a interface do admin do django, dai eu tava mostrando como o admin pode cadastrar o paciente.

**Comment by DaviMatheus** [comment]
implementados os psicologos com sucesso 🤓 👍
