### ISSUE TITLE
Atualização dos repositórios 

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#58]
### Descrição:

Atualização geral, documentos, github pages, escopo do projeto etc.

### Tarefas: 

- [x] Documento de Visão

- [x] Documento de Arquitetura

- [x] Product Backlog 

- [x] GitHub Pages

### Critério de aceitação:

Atualização dos documentos de acordo com o escopo atualizados na github pages

**Comment by antoniotoineto** [comment]
Documento de Visão e Arquitetura devidamente atualizados ✅ (ou quase devidamente 🙈)

@mibasFerraz @juninhigh @DaviMatheus @fernandes-natanael @art1505 @Abraao1231 Deêm uma olhada nesses documentos e vejam se tá faltando alguma coisa!!

**Comment by DaviMatheus** [comment]
Atualizei o tópico 5 de acordo com o Diagrama de Caso de Uso atualizado pelo @antoniotoineto, agr só falta atualizar o github pages, que já estou começando a mexer 🤓 👍

**Comment by DaviMatheus** [comment]
Atualizei os documentos na github pages, só falta mudar o visual de acordo com a identidade visual produzida pelo @fernandes-natanael  😼 💢

**Comment by NilvanPeres** [comment]
Acredito que todas as alterações do @antoniotoineto estão de acordo com nossa reunião de planejamento. @DaviMatheus  eu dei uma mexida no Doc de Arq pq no github-pages não estava aparecendo a primeira imagem, modifiquei de acordo com as outras que estão funcionando, e também a imagem do Canvas do projeto, dps atualiza esses dois documento no gh-pages que acredito que os problemas relacionadas as imagens que não aparecem lá serão sanados.

**Comment by mibasFerraz** [comment]
Dei uma olhada geral e está tudo show. Alterei um dado que estava errado na seção 2.2, onde falava que o Django utiliza o MVC e não o MTV.

**Comment by DaviMatheus** [comment]
Atualizei o Product Backlog de acordo com a [reunião de hoje](https://github.com/fga-eps-mds/2020.2-CheeryUP/blob/main/docs/AtaReunioes/Ata%20de%20Reuni%C3%B5es%2005/Reuni%C3%A3o_02.md) , ja colocando ele na github pages, aproveitando tambem consertei os bugs das imagens, agr só falta o @fernandes-natanael  implementar a identidade visual na github pages que a gente pode fechar a issue

**Comment by NilvanPeres** [comment]
Galera no meu gh-pages ainda não aparece a imagem do Canvas do Projeto, porém a imagem 2.0 foi do Doc de  Arquitetura foi consertada, e já consigo visualizar. Acredito que basta atualizar no gh-pages a parte do cavas, pq eu atualizei com a msm sintaxe das imagens que estão funcionando, @fernandes-natanael @DaviMatheus

**Comment by DaviMatheus** [comment]
arrumei @juninhigh confirma para mim se a imagem está aparecendo agora

**Comment by NilvanPeres** [comment]
> arrumei @juninhigh confirma para mim se a imagem está aparecendo agora

Agora está page 404 not found pra mim @DaviMatheus

**Comment by NilvanPeres** [comment]
Tudo certo agora @DaviMatheus , a imagem do Canvas está aparecendo normalmente... Boa ! :clap:  :clap:

**Comment by DaviMatheus** [comment]
😳 👍
