### ISSUE TITLE
Planejamento de Riscos

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#59]
### Descrição:
Complementar os riscos do TAP, criar um documento com mais detalhes sobre os riscos.
### Tarefas:

- [x] Criação do documento de riscos.

### Critério de aceitação:
O documento deve está de acordo com pré-elaborada no TAP, e com toda sua complementação.

**Comment by NilvanPeres** [comment]
Galera foi criado o documento, caso alguém identifique algum risco novo pode comentar nessa issue aqui, que irei adicionar.
@DaviMatheus @fernandes-natanael @Abraao1231 @art1505 @antoniotoineto @mibasFerraz. O documento ficará em review até hoje, amanhã será fechada a issue.

**Comment by DaviMatheus** [comment]
por mim, está tudo de acordo, os principais riscos já estão listados na minha opnião

**Comment by antoniotoineto** [comment]
> Galera foi criado o documento, caso alguém identifique algum risco novo pode comentar nessa issue aqui, que irei adicionar.
> @DaviMatheus @fernandes-natanael @Abraao1231 @art1505 @antoniotoineto @mibasFerraz. O documento ficará em review até hoje, amanhã será fechada a issue.

Dei uma olhada nos riscos. Foram todos listados muito bem, e alguns nos quais devemos nos atentar pra nunca acontecer!!! Comunicação e trabalho em equipe é a chave 👍

**Comment by art1505** [comment]
Documento visto! Os riscos estão bem condizentes com o que encontramos ou, eventualmente, encontraremos ao longo do projeto!
Além disso, as ações preventivas também foram expostas de forma clara e objetiva!
🤜🏽🤛🏽
