### ISSUE TITLE
Estudar metodologia AGILE/SCRUM

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#6]
- [x] Estudar Agile em geral

- [x] Estudar mais aprofundado o SCRUM

- [x] Documentar e Resumir para os colegas

**Comment by antoniotoineto** [comment]
AGILE
A expressão Agile vem da expressão Agile Software Development, o que seria uma Métodologia Ágil para realização de um projeto. Essa nova organização consiste em uma forma simples de gerenciar projetos complexos. Sendo assim, esse novo estilo de metodologia se difere das metodologias tradicionais por diversos fatores, dentre eles, a maior taxa de sucesso num processo inovador e complexo.
Por exemplo, em um cenário onde se tem total conhecimento dos requisitos do projeto e da tecnologia utilizada no processo, torna-se viável a utilização de uma metodologia tradicional, como as metodologias em cascata (uma etapa após a outra). No entanto, em um cenário mais caótico onde não temos pleno conhecimento dos requisitos e tecnologias, a melhor opção é a utilização de Métodologias Ágeis.

SCRUM
Scrum é uma Métodologia Ágil. Ou seja, é uma das formas de evitar processos longos e complicados que possam eventualmente falhar em algum momento. Além disso, Scrum é uma metodologia amplamente utilizada no mercado de trabalho, e com uma alta taxa de sucesso.
O Scrum possui 3 pilares fundamentais: 
- TRANSPARÊNCIA. Todos tem conhecimento dos requisitos de entrega e do andamento do processo.
- INSPEÇÃO. O projeto é constantemente inspecionado, seja através de reuniões diárias ou de Sprint Reviews.
- ADAPTAÇÃO. Tanto o processo quanto o produto final está sempre suscetível à mudanças, sendo assim é importante uma boa adaptação à tais modificações. 
Além disso, na metodologia Scrum é presente 3 papéis principais: o PRODUCT OWNER (dono do produto, quem detém o poder de decidir o que será entregue no final), o SCRUM MASTER (quem garante que as práticas do Scrum sejam realizadas para o bom funcionamento da metodologia) e por fim o DEV TEAM (grupo de desenvolvedores que irá "botar a mão na massa"). É importante ressaltar que a metodologia consiste numa equipe que se auto-organize e se ajude, além de decisões feitas em conjunto.
A dinâmica da metodologia funciona da seguinte forma: o Product Owner vai indicar a Visão do Produto, como ele o quer e onde quer chegar. A partir dessa visão, será feito uma lista de funcionalidades para que aquele produto se torne real, essa lista é chamada de PRODUCT BACKLOG e o Scrum Master ajuda o Product Owner a fazê-la. Além disso, o Scrum Master vai organizar essa lista de acordo com a prioridade de cada funcionalidade, as mais importantes serão feitas primeiro. Depois feito esse planejamento, o produto será entregado de forma gradativa, ou seja, "um pouco de cada vez". Essa entrega será feita através do SPRINT BACKLOG, que são espaços de tempos de 2 a 4 semanas, no qual ao final de cada Sprint, uma parte do produto é entregue. Para organizar e planejar os Sprints, será feita a SPRINT PLANNING e ao final de cada Sprint é feito o SPRINT REVIEW, para verificar a necessidade de mudanças no produto. Além disso, é praticamente certo que o produto sofrerá mudanças ao longo do processo, dessa forma, também é feita a RETROSPECTIVA para buscar melhoras no projeto. Após o término de todo este processo, o produto deve ser entregue contemplando todas as mudanças necessárias. Portanto, é um processo dinâmico que exige muito trabalho em equipe e comunicação.

Vídeos de apoio: https://www.youtube.com/watch?v=XfvQWnRgxG0&t=2s
                            https://www.youtube.com/watch?v=3jFhJXgURJw&t=3s
