### ISSUE TITLE
Estudo das ferramentas

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#61]
### Descrição:

Estudo geral das ferramentas e das tecnologias utilizadas no projeto.

### Tarefas:

- [x] Estudo das ferramentas do Backend

- [x] Estudo das ferramentas do Frontend

### Critério de aceitação:

Todos os integrantes do grupo dominarem bem os conceitos e os básicos de cada ferramenta.

**Comment by antoniotoineto** [comment]
Com a ajuda do brabo @juninhigh comecei a pegar prática nas ferramentas do front-end. No entanto, muita coisa pra aprender ainda 😼   Cheery Up!! 👍

**Comment by DaviMatheus** [comment]
O povo do BackEnd focou nessa semana estudar o framework django rest para a gente poder continuar o trabalho 🤓 👍
