### ISSUE TITLE
Finalização HomePage e pag de cadastro

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#63]
### Descrição:
Terminar NavBar e HomePage, e as páginas do front.
### Tarefas:

- [x] Terminar HomePage.
- [x] Criar tela de cadastro.

### Critério de aceitação:
Postar na issue o resultado final das páginas.

**Comment by NilvanPeres** [comment]
Tela de cadastro feita. 
<a href="https://ibb.co/StKhwPZ"><img src="https://i.ibb.co/c6NGh1s/Screenshot-from-2021-03-24-22-23-55.png" alt="Screenshot-from-2021-03-24-22-23-55" border="0"></a>

**Comment by fernandes-natanael** [comment]
Testei na minha maquina, funcionando perfeitamente
