### ISSUE TITLE
Planejamento de Horário

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/2020.2-CheeryUP#65]
### Descrição:
Essa issue será feitas em duas etapas. A primeira é a obtenção das datas de prova dos integrantes do grupo. A segunda parte é a criação de uma tabela com as semanas mais puxadas para que as sprints nessas datas sejam mais amenas.

### Tarefas:

- [x] Juntar todos os dados dos participantes do grupo.
- [x] Fazer uma tabela com as semanas de prova e adequar com as sprints.

### Critério de aceitação:
Ter uma tabela com todas as provas listadas durante as sprints.

**Comment by mibasFerraz** [comment]
Subi o arquivo dentro de docs > info, galera. Deêm uma olhada pra ver se ta certinho e comentem ae. @juninhigh @antoniotoineto @DaviMatheus @fernandes-natanael @Abraao1231 @art1505

**Comment by Abraao1231** [comment]
Ficou boa a organização da tabela junto com a legenda principalmente. Top demais

**Comment by DaviMatheus** [comment]
eai mano m ficou bom, agr só a gente  basear nisso e  ver quais horários a gente ta suave para resolver nosso projeto.
