### ISSUE TITLE
Estudo de Autenticação e Tokens no Django

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#70]
### Descrição:

Estudo da ferramenta para a continuação do projeto.

### Tarefas:

- [x] Estudar a ferramenta e os Tokens
- [x] Documentar para os colegas do grupo.

### Critério de aceitação:
- O Estudo deve ser feito com dedicação e compromisso para realmente entender o conteúdo .
- O Estudo estiver documentado e resumindo e todos os colegas estiverem compreendido o conteúdo.

**Comment by mibasFerraz** [comment]
### O que é a Autenticação com Token?
Autenticação com token com ou sem jwt (json web token) é um padrão de internet para criação de dados com assinatura definido pela RFC 7519, que regula como transmitir esses dados de forma compacta e segura. Os dados enviados para autenticação no nosso caso é o login e a senha. Após o login ser feito, o servidor que realiza a auntenticação retorna pro cliente um Token jwt assinado com o segredo interno da API para que o cliente possa fazer as requisições mantendo sua API segura.
Em suma, pra poder acessar os dados da API, precisa realizar e ser aceito pelo login.

Abaixo coloquei um vídeo bem didático em português de 20 min sobre o AuthTokenJWT e um em inglês muito bom também sobre o Token nativo do Django.

### Fontes:
https://www.youtube.com/watch?v=Wq6JqXqOzCE&t=23s
https://www.youtube.com/watch?v=LFV4MLe0ZzM&list=PLcM_74VFgRhrZZf3b7PaK3xQlfQi3kEkg&index=10

**Comment by DaviMatheus** [comment]
Entendi, vlw mano, com isso vamos conseguir realizar a autenticação e o login da melhor forma 😄

**Comment by Abraao1231** [comment]
Boa mano, vai ajudara bastante o pessoal do back na parte de login e cadastro.
