### ISSUE TITLE
Atualização dos Docs para a Release 1

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#71]
### Descrição:

Atualização de todos os documentos do repositório de acordo com o feedback das monitoras para uma boa First Release

### Tarefas:

- [x] Atualizar RoadMaps.
- [x] Atualizar gh-pages.
- [x] Atualizar TAP, e Documento de Arquitetura e outros.
- [x] Atualizar Product Backlog.

### Critério de aceitação:
Todos os membros devem contribuir nesses consertos.
Os concertos serem aprovados pelas monitoras

**Comment by DaviMatheus** [comment]
Atualizei os GitHub pages de acordo com as atualizações feitas pela equipe, valeu

**Comment by NilvanPeres** [comment]
Acredit que até o momento tá condizente com o nosso conhecimento. Bora ter um check-list pra esse Doc de Arq no próximo planning e pedir orientações com as monitoras para as melhorias
