### ISSUE TITLE
Refatoração Canvas

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#87]
### Descrição:
Refatoração e atualização do Canvas de acordo com o escopo atual do projeto a pedido da professora

### Tarefas:

- [x] Estudar e Ler o escopo para atualizar de forma correta o Canvas.
- [x] Atualizar o Canvas do projeto no repositorio e no github pages.

### Critérios de aceitação
 Revisão ortográfica.
 Pagina está no GitHub Pages

**Comment by NilvanPeres** [comment]
Gostei da atualização proposta pelo Abraão, na nossa daily de hoje discutiremos se há algo para podermos melhorar nesse canvas.

**Comment by DaviMatheus** [comment]
As mudanças foram feitas as revisões e colocada no github pages bom trabalho pessoal, continuem com essa organização que ta bonito
