### ISSUE TITLE
Reunião com psicológa

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#91]
### Descrição:
Retirar dúvida técnicas em relação a métricas do projeto.
### Tarefas:

- [x] Estabelecer principais dúvidas.
- [x] Estalecer métricas.
- [x] Principais critérios para montar o quadro de evolução dos pacientes

### Critério de aceitação:
Deve ser realizado uma reunião com a profissional escolhida.

**Comment by Abraao1231** [comment]
Foi feita hoje uma pequena reunião entre eu, Nilvan e o Lucas com a psicóloga Vania para estabelecermos melhores sintomas e características psicológicas para serem implementados nas consultas no qual também foi tratado sobre o tempo de evolução de um paciente com algum sintoma. Tudo isso para termos uma melhor ideia sobre a elaboração dos gráficos.

**Comment by antoniotoineto** [comment]
Muito importante essa reunião!! Agora nos resta decidir quais métricas serão abordadas na plataforma 😼

**Comment by NilvanPeres** [comment]
<a href="https://ibb.co/cTx9Q2Y"><img src="https://i.ibb.co/0JQLrYs/metricas.jpg" alt="metricas" border="0"></a>

**Comment by NilvanPeres** [comment]
<a href="https://ibb.co/59Rd83b"><img src="https://i.ibb.co/FWD9w1R/bla.jpg" alt="bla" border="0"></a>

**Comment by DaviMatheus** [comment]
--> Indicadores:
conhecimento doença
crises no espaço interino
exposição de risco
qualidade de sono
tentativa de suicidio
qualidade de escuta
maturidade emocional
qualidade nutritiva
auto medicação
intolerancia à frustração

--> Métricas:
problemas pessoais
humor
estabilidade de emoções
interesse pela vida
capacidade de situações dificeis
convívio familiar
energia e sono
convívio amigos
quadro geral (num 19)

**Comment by DaviMatheus** [comment]
Essas são as que a gente filtrou
