### ISSUE TITLE
correção de bug do registro do psicologo 

### ISSUE THREAD

**Issue by Abraao1231** [fga-eps-mds/2020.2-CheeryUP#93]
### Descreva o bug
O bug se trata sobre quando o psicologo é registrado na plataforma não conseguimos visualizar o código hash na pagina do admin

### Para reproduzir o bug
Passo-a-passo para reproduzir o comportamento do bug:
1. Vá para "http://0.0.0.0:8000/api/psicologo/"
2. Cadastre um psicologo
3. Vá para "http://0.0.0.0:8000/admin"
4. Veja o erro ao acessar o usuário cadastrado  

### Comportamento esperado
Que apareça uma senha criptografada na area de visualização do usuario na url de admin do projeto 

**Screenshots**

![image.png](https://images.zenhubusercontent.com/601c07725094444c5bd6fcf4/9d071077-8dd5-43cf-a47e-d490e3b1371e)

**Comment by Abraao1231** [comment]
acheeeeeeiiiii, tava usando o método "pop" onde não devia kkkkk.

**Comment by mibasFerraz** [comment]
O pop vem do python e serve pra remover um item. No caso a gente tava excluindo a senha kkkkkkk

**Comment by DaviMatheus** [comment]
Okay, eu ja vi o PR de vcs, vou testar e se estiver de acordo com o esperado vocês são brabo.
