### ISSUE TITLE
Reunião Cliente

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#98]
### Descrição:
Reunião com especialista, indicada por @CarlaRocha
### Tarefas:

- [x] Marcar Reunião.
- [x] Extrair principais pontos que profissional indicar.

### Critério de aceitação:
Resumo dos principais pontos, ou print's dos principais documentos.

**Comment by DaviMatheus** [comment]
A professora passou o contanto errado, então fizemos a reunião com os mesmos outros psicologos
